(()=>{
'use strict';
const C=window.JOTRIP_CONFIG||{};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=(v,d=0)=>Number.isFinite(Number(v))?Number(v).toFixed(d).replace(/\.0$/,''):'-';
const dt=d=>new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);
const tm=d=>new Intl.DateTimeFormat('vi-VN',{hour:'2-digit',minute:'2-digit',hour12:false}).format(d);
const age=t=>{const x=Date.parse(t);return Number.isFinite(x)?Math.max(0,Math.round((Date.now()-x)/60000)):null};
const ageText=a=>a==null?'-':a<60?`${a} phút`:`${Math.round(a/60)} giờ`;
const fresh=(t,limit)=>{const a=age(t);return a==null?['MISSING','missing',a]:a<=limit?['LIVE','live',a]:['STALE','stale',a]};
const icon=n=>`<i data-lucide="${n}"></i>`;
const localKey='jotrip-ops-v2';
const usersKey='jotrip-ops-users-v1';
const sessionKey='jotrip-ops-session-v1';

const ROLE_META={
  admin:{label:'Administrator',class:'admin',desc:'Toàn quyền hệ thống'},
  ops:{label:'Điều hành',class:'ops',desc:'Điều hành tour, công việc, khách và đối tác'},
  sales:{label:'Sales & Booking',class:'sales',desc:'Booking, khách hàng, đối tác'},
  guide:{label:'HDV / Host',class:'guide',desc:'Tour được giao, checklist và cập nhật hiện trường'},
  data:{label:'Data / Analyst',class:'data',desc:'Nguồn dữ liệu, báo cáo và live intelligence'},
  viewer:{label:'Chỉ xem',class:'viewer',desc:'Đọc thông tin, không thay đổi dữ liệu'},
  partner:{label:'Đối tác',class:'viewer',desc:'Chỉ phạm vi được giao - cần backend để enforce'}
};
const PERMS={
  admin:['*'],
  ops:['overview','today','tasks','tours','customers','partners','people','airport','ferries','weather','map','data','reports','write_ops'],
  sales:['overview','today','tours','customers','partners','airport','reports','write_sales'],
  guide:['today','tasks','tours','airport','weather','map','update_assigned'],
  data:['overview','airport','weather','map','data','reports'],
  viewer:['overview','today','airport','weather','reports'],
  partner:['today','tours','tasks']
};
const can=(p)=>{const r=S.user?.role||'viewer', arr=PERMS[r]||[];return arr.includes('*')||arr.includes(p)};

function seedOps(){return{
  tours:[
    {id:'JT-ISL-001',time:'07:00',name:'3 đảo',guests:18,host:'Minh / Hằng',vehicle:'Cano 01',readiness:100,status:'Đang chạy',issue:'',nation:'Việt'},
    {id:'JT-PRV-012',time:'08:30',name:'Private Island Day',guests:8,host:'Tùng / Quân',vehicle:'Cano 03',readiness:80,status:'Sắp chạy',issue:'Thiếu xe',nation:'Hàn'},
    {id:'JT-CITY-021',time:'09:00',name:'City & Sunset Town',guests:24,host:'Lan / Phương',vehicle:'Xe 07',readiness:100,status:'Đang chạy',issue:'',nation:'Khác'},
    {id:'JT-FISH-005',time:'13:00',name:'Câu cá lớn',guests:6,host:'Nam / Ken',vehicle:'Cano 02',readiness:60,status:'Sắp chạy',issue:'Theo dõi biển',nation:'Việt'},
    {id:'JT-ISL-018',time:'14:00',name:'3 đảo Nam',guests:20,host:'Huy / Thảo',vehicle:'Cano 04',readiness:100,status:'Sắp chạy',issue:'',nation:'Hàn'},
    {id:'JT-SUN-007',time:'16:00',name:'Sunset Town & cáp treo',guests:28,host:'Hoàng / Linh',vehicle:'Xe 15',readiness:90,status:'Sắp chạy',issue:'',nation:'Khác'},
    {id:'JT-NIGHT-003',time:'17:30',name:'Night Fishing',guests:6,host:'Nam / Quân',vehicle:'Cano 05',readiness:100,status:'Sắp chạy',issue:'',nation:'Việt'}
  ],
  tasks:[
    {id:'TSK-001',level:'high',title:'Xác nhận phương án biển JT-FISH-005',detail:'Theo dõi cửa vận hành và xác nhận với tài công.',owner:'Ken Anh',status:'open'},
    {id:'TSK-002',level:'high',title:'Thiếu xe cho JT-PRV-012',detail:'Cần xác nhận phương tiện trước giờ đón.',owner:'Điều hành',status:'open'},
    {id:'TSK-003',level:'medium',title:'Rà chuyến bay đoàn Hàn',detail:'Đối chiếu Airport Live trước giờ đón.',owner:'Lan Anh',status:'open'}
  ],
  activity:[
    ['Ngọc Hà','cập nhật trạng thái tour JT-ISL-001','5 phút trước'],
    ['Minh Quân','thêm booking BKG-20260915-01','12 phút trước'],
    ['Hệ thống','đồng bộ dữ liệu Airport','18 phút trước'],
    ['Lan Anh','cập nhật hồ sơ khách KH-281','25 phút trước']
  ]
}}
function seedUsers(){return[
  {id:'USR-001',name:'Ken Anh',email:'admin@jotrip.local',role:'admin',status:'active',scope:'Toàn hệ thống',last:'Hiện tại'},
  {id:'USR-002',name:'Lan Anh',email:'lan@jotrip.local',role:'ops',status:'active',scope:'Phú Quốc',last:'14 phút trước'},
  {id:'USR-003',name:'Minh Quân',email:'minh@jotrip.local',role:'sales',status:'active',scope:'Booking & khách',last:'1 giờ trước'},
  {id:'USR-004',name:'Nam',email:'nam@jotrip.local',role:'guide',status:'active',scope:'Tour được giao',last:'32 phút trước'}
]}
function loadJSON(k,fallback){try{return JSON.parse(localStorage.getItem(k))||fallback}catch{return fallback}}
const S={view:'today',weather:null,aqi:null,tide:null,airport:null,health:null,ops:loadJSON(localKey,seedOps()),users:loadJSON(usersKey,seedUsers()),user:null};
function saveOps(){localStorage.setItem(localKey,JSON.stringify(S.ops))}
function saveUsers(){localStorage.setItem(usersKey,JSON.stringify(S.users))}
function initUser(){let id=localStorage.getItem(sessionKey);S.user=S.users.find(u=>u.id===id&&u.status==='active')||S.users[0];localStorage.setItem(sessionKey,S.user.id)}

function roots(branch){const b=branch||'main';const repo=C.repo||'kenzuko/Jotrip-Lab';return [`https://raw.githubusercontent.com/${repo}/${b}`,`https://raw.githubusercontent.com/${repo}/main`].filter((v,i,a)=>a.indexOf(v)===i)}
async function fetchJSON(url){try{const r=await fetch(url+(url.includes('?')?'&':'?')+'v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));return await r.json()}catch{return null}}
async function fetchFromRoots(rs,path){for(const r of rs){const data=await fetchJSON(`${r}/${path}`);if(data)return data}return null}
async function syncUpstreams(){
  const wr=roots(C.weatherBranch), ar=roots(C.airportBranch);
  const [w,q,t,a,h]=await Promise.all([
    fetchFromRoots(wr,'weather/dashboard-data.json'),
    fetchFromRoots(wr,'weather/air-quality.json'),
    fetchFromRoots(wr,'weather/tide.json'),
    fetchFromRoots(ar,'data/sunairport/latest.json'),
    fetchFromRoots(ar,'data/sunairport/health.json')
  ]);
  if(w)S.weather=w;if(q)S.aqi=q;if(t)S.tide=t;if(a)S.airport=a;if(h)S.health=h;
  renderChrome();render();
}
function weatherTime(){return S.weather?.generated_at||S.weather?.created_at||null}
function airportTime(){return S.airport?.collected_at_vn||S.airport?.collected_at||S.health?.last_successful_run||null}
function renderChrome(){
  const wf=fresh(weatherTime(),C.staleMinutes?.weather||180), af=fresh(airportTime(),C.staleMinutes?.airport||30);
  const state=wf[1]==='missing'||af[1]==='missing'?'danger':wf[1]==='stale'||af[1]==='stale'?'warn':'ok';
  const dot=$('#healthChip .dot');if(dot)dot.className='dot '+state;
  $('#systemText').textContent=state==='ok'?'Nguồn vận hành ổn định':state==='warn'?'Có nguồn đang chậm':'Có nguồn chưa tải';
  $('#healthMeta').textContent=`Weather ${wf[0]} · Airport ${af[0]}`;
  $('#sidebarSync').textContent=state==='ok'?'Nguồn đang ổn định':state==='warn'?'Có nguồn stale':'Kiểm tra nguồn';
  $('#taskBadge').textContent=S.ops.tasks.filter(x=>x.status==='open').length;
  $('#airportBadge').textContent=S.airport?.counts?.arrivals??S.airport?.records?.filter?.(x=>x.direction==='arrival').length??'-';
  $('#sourceBadge').textContent=state==='ok'?'LIVE':state.toUpperCase();
  $('#weatherDot').className='source-dot '+wf[1];
  const p=S.weather?.points?.duong_dong;$('#topWeather').innerHTML=`${icon('sun-medium')}<div><b>${p?.temperature!=null?fmt(p.temperature)+'°C':'--°C'}</b><small>Phú Quốc</small></div>`;
  $('#topAvatar').textContent=initials(S.user?.name||'User');$('#topUserName').textContent=S.user?.name||'User';$('#topUserRole').textContent=ROLE_META[S.user?.role]?.label||S.user?.role||'-';
  applyPermissions();refreshIcons();
}
function applyPermissions(){
  $$('.nav-item[data-view]').forEach(b=>{const v=b.dataset.view;b.hidden=!(can(v)||(v==='accounts'&&can('*'))||(v==='settings'&&can('*')))});
}
function initials(name){return String(name).split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase()}
function refreshIcons(){requestAnimationFrame(()=>window.lucide?.createIcons?.({attrs:{'stroke-width':1.8}}))}
function toast(msg){const el=document.createElement('div');el.className='toast';el.innerHTML=`${icon('sparkles')}<span>${esc(msg)}</span>`;$('#toastStack').append(el);refreshIcons();setTimeout(()=>el.remove(),2800)}
function sourceBanner(){const w=fresh(weatherTime(),C.staleMinutes?.weather||180),a=fresh(airportTime(),C.staleMinutes?.airport||30);return `<div class="source-banner"><span class="dot ${w[1]==='live'?'ok':w[1]==='stale'?'warn':'danger'}"></span><strong>Weather ${w[0]}</strong><span>${ageText(w[2])}</span><span class="dot ${a[1]==='live'?'ok':a[1]==='stale'?'warn':'danger'}"></span><strong>Airport ${a[0]}</strong><span>${ageText(a[2])}</span><span class="spacer"></span><span class="readonly-chip">READ ONLY UPSTREAM</span></div>`}
function decisionClass(x){x=String(x||'').toUpperCase();return x==='GO'?'ok':x.includes('WATCH')||x.includes('MODIFY')?'warn':x.includes('CANCEL')||x.includes('HOLD')?'danger':'neutral'}
function decisionLabel(x){x=String(x||'NOT_ISSUED').toUpperCase();return x==='NOT_ISSUED'?'CHƯA PHÁT':x.replaceAll('_',' ')}
function commandStrip(){const open=S.ops.tasks.filter(x=>x.status==='open'),issues=S.ops.tours.filter(x=>x.issue),soon=S.ops.tours.filter(x=>x.status==='Sắp chạy');return `<div class="command-strip"><article class="brief-card"><small>SHIFT BRIEF · ${tm(new Date())}</small><h2>${S.ops.tours.length} tour · ${S.ops.tours.reduce((a,x)=>a+x.guests,0)} khách · ${open.length} việc mở</h2><p>${issues.length?`${issues.length} tour cần theo dõi trước giờ khởi hành.`:'Không có exception lớn trong dữ liệu nội bộ hiện tại.'}</p></article><article class="signal-card danger"><div class="signal-icon">${icon('triangle-alert')}</div><div><strong>${open.filter(x=>x.level==='high').length}</strong><b>Cần xử lý ngay</b><small>exception ưu tiên</small></div></article><article class="signal-card"><div class="signal-icon">${icon('clock-3')}</div><div><strong>${soon.length}</strong><b>Sắp chạy</b><small>trong ngày</small></div></article><article class="signal-card ok"><div class="signal-icon">${icon('circle-check')}</div><div><strong>${S.ops.tours.filter(x=>x.readiness===100).length}</strong><b>Ready 100%</b><small>tour đã đủ điều kiện</small></div></article></div>`}
function kpi(i,v,l,s,c=''){return `<article class="kpi ${c}"><div class="kpi-icon">${icon(i)}</div><div><h3>${v}</h3><p>${l}</p><small>${s}</small></div></article>`}
function conditions(){const p=S.weather?.points||{},q=S.aqi?.points||{},t=S.tide?.points||{},globalDecision=S.weather?.decision;const keys=['duong_dong','an_thoi','ganh_dau'];return `<section class="panel"><div class="panel-head"><h2>Điều kiện vận hành</h2><small>${weatherTime()?'cập nhật '+tm(new Date(weatherTime())):'đang tải'}</small><span class="spacer"></span><button class="btn" data-view="weather">Xem sâu →</button></div><div class="conditions">${keys.map(k=>{const z=p[k]||{},a=q[k]||{},v=t[k]||{};const d=z.decision||globalDecision;return `<div class="condition"><h4>${esc(z.name||({duong_dong:'Dương Đông',an_thoi:'An Thới',ganh_dau:'Gành Dầu'}[k]))}</h4><div class="temp">${z.temperature!=null?fmt(z.temperature)+'°C':'--'}</div><div class="metric-list"><div class="metric"><span>Gió</span><b>${fmt(z.wind,1)} km/h</b></div><div class="metric"><span>Sóng Hs</span><b>${fmt(z.wave,2)} m</b></div><div class="metric"><span>Mưa</span><b>${fmt(z.rain,1)} mm</b></div><div class="metric"><span>AQI*</span><b>${a.aqi_us??'-'}</b></div><div class="metric"><span>Triều</span><b>${v.trend==='FALLING'?'↓ xuống':v.trend==='RISING'?'↑ lên':'-'}</b></div></div><span class="status-pill ${decisionClass(d)}">${esc(decisionLabel(d))}</span></div>`}).join('')}</div></section>`}
function timeline(){const flight=(S.airport?.records||[]).find(x=>x.direction==='arrival');return `<section class="panel"><div class="panel-head"><h2>Timeline vận hành</h2><span class="eyebrow">06:00 - 22:00</span><span class="spacer"></span><button class="btn">${icon('sliders-horizontal')} Bộ lọc</button></div><div class="timeline"><div class="timeline-grid"><div class="time-head">Thời gian</div>${['06','08','10','12','14','16','18','20','22'].map(x=>`<div class="time-head">${x}:00</div>`).join('')}${[
['Tour du lịch',['3 đảo','Private Island','','Câu cá','','Sunset Town','','Night Fishing','']],
['Đón/tiễn sân bay',['',flight?.operating_flight_number||'', '', '', '', '', '', '', '']],
['Tàu & phà',['PQ Express','','Superdong','','PQ Express','','Superdong','','']],
['Xe',['Xe 01-06','','','Xe 07-12','','','Xe 13-18','','']],
['Cano',['Cano 01-02','','','Cano 03-04','','','Cano 05-06','','']],
['HDV / Host',['Nhóm A','','Nhóm B','','Nhóm C','','Nhóm D','','']]
].map((r,ri)=>`<div class="row-label">${r[0]}</div>${r[1].map(x=>`<div class="timeline-cell">${x?`<div class="event ${ri===1?'blue':ri===2?'gray':ri===0?'green':'gold'}">${esc(x)}</div>`:''}</div>`).join('')}`).join('')}</div></div></section>`}
function toursTable(compact=false){return `<section class="panel"><div class="panel-head"><h2>${compact?'Tour có vấn đề':'Danh sách tour hôm nay'} (${S.ops.tours.length})</h2><span class="spacer"></span>${can('write_ops')||can('write_sales')?`<button class="btn gold" id="newTour">${icon('plus')} Tạo tour</button>`:''}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Giờ</th><th>Mã tour</th><th>Hành trình</th><th>SL khách</th><th>Quốc tịch</th><th>HDV / Host</th><th>Phương tiện</th><th>Readiness</th><th>Trạng thái</th><th>Vấn đề</th><th></th></tr></thead><tbody>${S.ops.tours.map(x=>`<tr><td>${esc(x.time)}</td><td><b>${esc(x.id)}</b></td><td>${esc(x.name)}</td><td>${x.guests}</td><td>${esc(x.nation||'-')}</td><td>${esc(x.host)}</td><td>${esc(x.vehicle)}</td><td><span class="readiness ${x.readiness<70?'low':x.readiness<100?'mid':''}">${x.readiness}%</span></td><td><span class="row-status ${x.status!=='Đang chạy'?'pending':''}">${esc(x.status)}</span></td><td>${x.issue?`<span style="color:#c9443d">${icon('triangle-alert')} ${esc(x.issue)}</span>`:'--'}</td><td><button class="icon-btn open-tour" data-id="${esc(x.id)}">${icon('ellipsis')}</button></td></tr>`).join('')}</tbody></table></div></section>`}
function alerts(){const af=fresh(airportTime(),C.staleMinutes?.airport||30), arr=[];if(af[1]==='stale')arr.push(['Nguồn Airport đang cũ',`Snapshot gần nhất cách ${ageText(af[2])}. Không coi là realtime.`,'high']);S.ops.tasks.filter(x=>x.status==='open').slice(0,4-arr.length).forEach(x=>arr.push([x.title,x.detail,x.level]));return `<section class="panel"><div class="panel-head"><h2>Cảnh báo & việc cần xử lý</h2><span class="spacer"></span><button class="btn" data-view="tasks">Xem tất cả →</button></div><div class="alert-list">${arr.map((x,i)=>`<div class="alert-item"><div class="alert-num ${x[2]==='medium'?'warn':''}">${i+1}</div><div><b>${esc(x[0])}</b><p>${esc(x[1])}</p></div></div>`).join('')}</div></section>`}
function activity(){return `<section class="panel"><div class="panel-head"><h2>Hoạt động gần đây</h2></div><div class="activity-list">${S.ops.activity.map(x=>`<div class="activity-item"><div class="avatar">${initials(x[0])}</div><div><b>${esc(x[0])}</b><p>${esc(x[1])}</p></div><time>${esc(x[2])}</time></div>`).join('')}</div></section>`}
function sourceRows(){const w=fresh(weatherTime(),C.staleMinutes?.weather||180),q=fresh(S.aqi?.sampled_time,C.staleMinutes?.airQuality||360),t=fresh(S.tide?.generated_at,C.staleMinutes?.tide||180),a=fresh(airportTime(),C.staleMinutes?.airport||30);return [['Weather Lab',S.weather?.completeness!=null?S.weather.completeness+'%':'-',w],['AQI / CAMS',S.aqi?.status||'-',q],['Triều / Copernicus',S.tide?.status||'-',t],['Airport Live',S.airport?.quality?.passed?'QA PASS':S.health?.qa_passed?'QA PASS':'-',a]]}
function healthPanel(){return `<section class="panel"><div class="panel-head"><h2>Chất lượng nguồn dữ liệu</h2><span class="spacer"></span><button class="btn" data-view="data">Xem chi tiết →</button></div><div class="source-list">${sourceRows().map(x=>`<div class="source-row"><b>${esc(x[0])}</b><span>${esc(x[1])}</span><span class="source-state ${x[2][1]}">${x[2][0]}</span></div>`).join('')}</div></section>`}
function today(){const total=S.ops.tours.reduce((a,x)=>a+x.guests,0),run=S.ops.tours.filter(x=>x.status==='Đang chạy').length,bad=S.ops.tours.filter(x=>x.issue).length;return `${sourceBanner()}${commandStrip()}<div class="page-head"><div><h1>Điều hành hôm nay</h1><div class="subtitle">Một bàn điều hành - ưu tiên exception, readiness và tác động</div></div><div class="date-control"><button>‹</button><span>${dt(new Date())}</span><button>›</button></div><div class="head-actions"><button class="btn">${icon('filter')} Bộ lọc</button><button class="btn primary">${icon('gantt-chart')} Timeline</button><button class="btn">${icon('table-2')} Bảng</button></div></div><div class="kpi-grid">${kpi('calendar-days',S.ops.tours.length,'Tour trong ngày',`${run} đang chạy`)}${kpi('users',total,'Tổng khách','Theo dữ liệu nội bộ')}${kpi('circle-check',run,'Đang chạy','Operations Center','ok')}${kpi('triangle-alert',bad,'Tour có vấn đề','Cần xử lý ngay','danger')}${kpi('bus-front',18,'Xe đang sử dụng','Còn trống 6 xe','ok')}${kpi('ship-wheel',6,'Cano trong ngày','Đang dùng 4','info')}</div><div class="grid-main"><div class="stack">${timeline()}${toursTable()}</div><div class="stack">${conditions()}${alerts()}${activity()}${healthPanel()}</div></div>`}
function overview(){return `${sourceBanner()}${commandStrip()}<div class="page-head"><div><h1>Tổng quan JoTrip</h1><div class="subtitle">Tình hình điều hành, nguồn dữ liệu và công việc trong một màn hình</div></div></div><div class="grid-main"><div class="stack">${toursTable()}${timeline()}</div><div class="stack">${alerts()}${conditions()}${healthPanel()}</div></div>`}
function tasksView(){return `<div class="page-head"><div><h1>Việc cần làm</h1><div class="subtitle">Exception-first - việc chưa đóng được ưu tiên trước</div></div>${can('write_ops')?`<div class="head-actions"><button class="btn gold" id="newTask">${icon('plus')} Thêm việc</button></div>`:''}</div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Mức</th><th>Việc</th><th>Chi tiết</th><th>Phụ trách</th><th>Trạng thái</th><th></th></tr></thead><tbody>${S.ops.tasks.map(x=>`<tr><td><span class="role-chip ${x.level==='high'?'admin':'ops'}">${x.level==='high'?'KHẨN':'THEO DÕI'}</span></td><td><b>${esc(x.title)}</b></td><td>${esc(x.detail)}</td><td>${esc(x.owner)}</td><td><span class="account-status ${x.status==='done'?'':'disabled'}">${x.status==='done'?'Đã xong':'Đang mở'}</span></td><td>${can('write_ops')?`<button class="btn close-task" data-id="${x.id}">${x.status==='done'?'Mở lại':'Đóng việc'}</button>`:''}</td></tr>`).join('')}</tbody></table></div></section>`}
function toursView(){return `<div class="page-head"><div><h1>Tour & Booking</h1><div class="subtitle">Không tách app - xử lý tour, khách, phương tiện và issue ngay trong Operations Center</div></div></div>${toursTable()}`}
function weatherView(){const p=S.weather?.points||{},q=S.aqi?.points||{},t=S.tide?.points||{};return `${sourceBanner()}<div class="page-head"><div><h1>Weather & Marine</h1><div class="subtitle">Trang chuyên sâu - dashboard chỉ đọc output mới nhất từ Weather Lab</div></div><div class="head-actions">${C.weatherWebUrl?`<a class="btn primary" href="${C.weatherWebUrl}" target="_blank">Mở Weather Lab ↗</a>`:'<span class="readonly-chip">READ ONLY</span>'}</div></div><div class="external-card"><div class="external-icon">${icon('cloud-sun')}</div><div><h3>Upstream độc lập</h3><p>Không sửa forecast, collector, snapshot hay decision logic từ Dashboard. Khi upstream đổi schema, adapter chỉ đọc phần nhận diện được và hạ trạng thái khi thiếu.</p></div></div><div class="feature-grid">${['duong_dong','an_thoi','ganh_dau'].map(k=>{const z=p[k]||{},a=q[k]||{},v=t[k]||{};return `<div class="feature-card"><h3>${esc(z.name||k)}</h3><p>Gió ${fmt(z.wind,1)} km/h · Sóng ${fmt(z.wave,2)} m<br>Mưa ${fmt(z.rain,1)} mm · AQI ${a.aqi_us??'-'}<br>Triều ${v.current_height_m!=null?fmt(v.current_height_m,3)+' m':'-'} · ${esc(v.trend||'-')}</p></div>`}).join('')}</div>`}
function airportView(){const a=S.airport,r=a?.records||[],f=fresh(airportTime(),C.staleMinutes?.airport||30);return `${sourceBanner()}<div class="page-head"><div><h1>Airport Live</h1><div class="subtitle">Trang chuyên sâu - dữ liệu sân bay đọc trực tiếp, không ghi ngược</div></div><div class="head-actions"><a class="btn primary" href="${C.airportWebUrl}" target="_blank" rel="noopener">Mở Airport Live ↗</a></div></div><div class="external-card"><div class="external-icon">${icon('plane')}</div><div><h3>${f[0]} · ${r.length} movement</h3><p>${S.health?.final_evidence_status||'Đang đọc snapshot normalized'} · tuổi dữ liệu ${ageText(f[2])}</p></div><a class="btn primary" href="${C.airportWebUrl}" target="_blank">Airport Live</a></div><section class="panel" style="margin-top:10px"><div class="panel-head"><h2>Chuyến gần nhất</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Loại</th><th>Chuyến</th><th>Hãng</th><th>Nơi đi/đến</th><th>Giờ</th><th>Trạng thái</th></tr></thead><tbody>${r.slice(0,18).map(x=>`<tr><td>${x.direction==='arrival'?'Đến':'Đi'}</td><td><b>${esc(x.operating_flight_number)}</b></td><td>${esc(x.carrier||'-')}</td><td>${esc(x.station||'-')}</td><td>${esc(x.scheduled_time||'-')}</td><td>${esc(x.status||'-')}</td></tr>`).join('')}</tbody></table></div></section>`}
function dataView(){return `<div class="page-head"><div><h1>Dữ liệu & nguồn</h1><div class="subtitle">Phân biệt rõ LIVE, STALE, MISSING và dữ liệu local</div></div></div><section class="panel"><div class="panel-head"><h2>Source health</h2></div><div class="source-list">${sourceRows().map(x=>`<div class="source-row"><b>${esc(x[0])}</b><span>${esc(x[1])}</span><span class="source-state ${x[2][1]}">${x[2][0]} · ${ageText(x[2][2])}</span></div>`).join('')}</div></section>`}
function placeholder(title,iconName,text){return `<div class="view-placeholder"><div class="section-intro"><div class="intro-icon">${icon(iconName)}</div><div><h2>${esc(title)}</h2><p>${esc(text)}</p></div></div></div>`}
function accountsView(){if(!can('*'))return placeholder('Không có quyền','shield-x','Tài khoản hiện tại không được phép quản trị người dùng.');const roles=['admin','ops','sales','guide','data','viewer','partner'];const matrix=[['Xem vận hành','✓','✓','✓','✓','✓','✓'],['Sửa tour/công việc','✓','✓','—','Giới hạn','—','—'],['Booking & khách','✓','✓','✓','Giới hạn','—','—'],['Nguồn dữ liệu','✓','✓','—','—','✓','—'],['Tạo tài khoản','✓','—','—','—','—','—'],['Cài đặt hệ thống','✓','—','—','—','—','—']];return `<div class="page-head"><div><h1>Tài khoản & phân quyền</h1><div class="subtitle">RBAC theo vai trò, nguyên tắc quyền tối thiểu</div></div><div class="head-actions"><button class="btn gold" id="newUser">${icon('user-plus')} Tạo tài khoản</button></div></div><div class="permission-layout"><div class="stack"><section class="panel"><div class="panel-head"><h2>Người dùng (${S.users.length})</h2><span class="spacer"></span><span class="eyebrow">ADMIN ONLY</span></div><div class="account-list">${S.users.map(u=>`<div class="account-row"><div class="avatar">${initials(u.name)}</div><div class="account-meta"><b>${esc(u.name)}</b><small>${esc(u.email)}</small></div><span class="role-chip ${ROLE_META[u.role]?.class||''}">${esc(ROLE_META[u.role]?.label||u.role)}</span><div class="account-meta hide-mobile"><b>${esc(u.scope||'-')}</b><small>${esc(u.last||'-')}</small></div><button class="icon-btn edit-user" data-id="${u.id}">${icon('ellipsis')}</button></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>Ma trận quyền</h2></div><div class="table-wrap"><table class="permission-matrix"><thead><tr><th>Khả năng</th><th>Admin</th><th>Điều hành</th><th>Sales</th><th>HDV</th><th>Data</th><th>Viewer</th></tr></thead><tbody>${matrix.map(r=>`<tr>${r.map((c,i)=>`<td class="${i&&c==='✓'?'perm-yes':i&&c==='—'?'perm-no':''}">${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section></div><div class="stack"><section class="panel"><div class="panel-head"><h2>Authentication</h2></div><div style="padding:11px"><div class="auth-mode"><div><b>Provider</b><br><span>${esc(C.auth?.provider||'supabase')}</span></div><span class="badge">${C.auth?.mode==='local-preview'?'LOCAL PREVIEW':'CONNECTED'}</span></div></div><div class="security-note"><b>Lưu ý bảo mật:</b> GitHub Pages là static. Danh sách tài khoản/role hiện dùng local preview để hoàn thiện UX, chưa phải lớp bảo vệ thật. Khi nối Auth provider, quyền phải được enforce ở backend/RLS - không chỉ ẩn nút ở frontend.</div></section><section class="panel"><div class="panel-head"><h2>Vai trò</h2></div><div class="source-list">${roles.map(r=>`<div class="source-row"><b>${ROLE_META[r].label}</b><span>${ROLE_META[r].desc}</span><span class="role-chip ${ROLE_META[r].class}">${r}</span></div>`).join('')}</div></section></div></div>`}
function settingsView(){return `<div class="page-head"><div><h1>Cài đặt</h1><div class="subtitle">Cấu hình hiển thị và kết nối. Upstream Weather/Airport vẫn read-only.</div></div></div><div class="feature-grid"><div class="feature-card"><h3>Brand system</h3><p>JoTrip Yellow #FCBC12 · JoTrip Green #77944C · Forest Ops UI.</p></div><div class="feature-card"><h3>Weather upstream</h3><p>${esc(C.weatherBranch||'-')} · không ghi dữ liệu.</p></div><div class="feature-card"><h3>Airport upstream</h3><p>${esc(C.airportBranch||'-')} · không ghi dữ liệu.</p></div></div>`}
function render(){let html='';switch(S.view){case'overview':html=overview();break;case'today':html=today();break;case'tasks':html=tasksView();break;case'tours':html=toursView();break;case'weather':html=weatherView();break;case'airport':html=airportView();break;case'data':html=dataView();break;case'accounts':html=accountsView();break;case'settings':html=settingsView();break;case'customers':html=placeholder('Khách hàng','users','Hồ sơ khách, đoàn, liên hệ và lịch sử booking sẽ xử lý ngay trong Operations Center.');break;case'partners':html=placeholder('Đối tác','handshake','Quản lý xác nhận, năng lực, liên hệ và phạm vi dịch vụ của đối tác.');break;case'people':html=placeholder('Nhân sự & công việc','briefcase-business','Phân ca, người phụ trách, công việc và bàn giao ca.');break;case'ferries':html=placeholder('Tàu & phà','ship','Chưa gắn source live riêng. Không hiển thị dữ liệu giả.');break;case'map':html=placeholder('Bản đồ vận hành','map','Lớp bản đồ sẽ đọc vị trí/điểm vận hành và live intelligence khi nguồn sẵn sàng.');break;case'reports':html=placeholder('Báo cáo','chart-no-axes-combined','Báo cáo vận hành, source health và hoạt động theo ngày/ca.');break;default:html=today()}$('#pageRoot').innerHTML=html;bindView();refreshIcons()}
function setView(v){if(v==='accounts'&&!can('*'))return; if(!can(v)&&!['settings'].includes(v)&&!can('*'))return toast('Tài khoản này không có quyền mở mục đó.');S.view=v;$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('#mobileDock [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#sidebar').classList.remove('open');render()}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modalBackdrop').hidden=false;refreshIcons()}
function closeModal(){$('#modalBackdrop').hidden=true}
function drawer(title,kicker,body){$('#drawerTitle').textContent=title;$('#drawerKicker').textContent=kicker;$('#drawerBody').innerHTML=body;$('#drawerBackdrop').hidden=false;$('#drawer').classList.add('open');$('#drawer').setAttribute('aria-hidden','false');refreshIcons()}
function closeDrawer(){$('#drawerBackdrop').hidden=true;$('#drawer').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true')}
function userForm(u={}){return `<div class="form-grid"><div class="field"><label>Họ tên</label><input id="fName" value="${esc(u.name||'')}"></div><div class="field"><label>Email / Username</label><input id="fEmail" value="${esc(u.email||'')}"></div><div class="field"><label>Vai trò</label><select id="fRole">${Object.entries(ROLE_META).map(([k,v])=>`<option value="${k}" ${u.role===k?'selected':''}>${esc(v.label)}</option>`).join('')}</select></div><div class="field"><label>Phạm vi</label><input id="fScope" value="${esc(u.scope||'Phú Quốc')}"></div><div class="field full"><label>Trạng thái</label><select id="fStatus"><option value="active" ${u.status!=='disabled'?'selected':''}>Hoạt động</option><option value="disabled" ${u.status==='disabled'?'selected':''}>Khóa</option></select></div></div><div class="form-actions"><button class="btn" id="cancelForm">Hủy</button><button class="btn gold" id="saveUser">${icon('save')} Lưu tài khoản</button></div>`}
function bindUserForm(id){$('#cancelForm').onclick=closeModal;$('#saveUser').onclick=()=>{const name=$('#fName').value.trim(),email=$('#fEmail').value.trim();if(!name||!email)return toast('Cần nhập tên và email.');let u=id?S.users.find(x=>x.id===id):null;if(!u){u={id:'USR-'+String(Date.now()).slice(-6),last:'Chưa đăng nhập'};S.users.push(u)}Object.assign(u,{name,email,role:$('#fRole').value,scope:$('#fScope').value.trim()||'Phú Quốc',status:$('#fStatus').value});saveUsers();closeModal();renderChrome();render();toast('Đã lưu tài khoản trong local preview.')}}
function tourDrawer(t){drawer(t.id,'TOUR DETAIL',`<div class="drawer-card"><h4>${esc(t.name)}</h4><div class="detail-grid"><div class="detail-item"><span>Giờ</span><b>${esc(t.time)}</b></div><div class="detail-item"><span>Khách</span><b>${t.guests}</b></div><div class="detail-item"><span>HDV / Host</span><b>${esc(t.host)}</b></div><div class="detail-item"><span>Phương tiện</span><b>${esc(t.vehicle)}</b></div><div class="detail-item"><span>Readiness</span><b>${t.readiness}%</b></div><div class="detail-item"><span>Vấn đề</span><b>${esc(t.issue||'Không')}</b></div></div></div><div class="drawer-card"><h4>Readiness checklist</h4><p style="font-size:9px;line-height:1.7;margin:0">Khách ✓ · HDV ✓ · Vé ✓ · Phương tiện ${t.issue==='Thiếu xe'?'✕':'✓'} · Weather ${t.issue==='Theo dõi biển'?'WATCH':'✓'}</p></div><div style="display:flex;gap:6px;flex-wrap:wrap">${can('write_ops')?'<button class="btn gold">Cập nhật</button>':''}<button class="btn">Mở khách</button><button class="btn">Liên hệ HDV</button></div>`)}
function bindView(){
  $$('[data-view]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;if(v)setView(v)}));
  $$('.open-tour').forEach(b=>b.onclick=()=>{const t=S.ops.tours.find(x=>x.id===b.dataset.id);if(t)tourDrawer(t)});
  $('#newUser')?.addEventListener('click',()=>{modal('Tạo tài khoản',userForm({role:'ops',status:'active'}));bindUserForm()});
  $$('.edit-user').forEach(b=>b.onclick=()=>{const u=S.users.find(x=>x.id===b.dataset.id);drawer(u.name,'ACCOUNT',`<div class="drawer-card"><h4>${esc(ROLE_META[u.role]?.label||u.role)}</h4><div class="detail-grid"><div class="detail-item"><span>Email</span><b>${esc(u.email)}</b></div><div class="detail-item"><span>Phạm vi</span><b>${esc(u.scope)}</b></div><div class="detail-item"><span>Trạng thái</span><b>${u.status==='active'?'Hoạt động':'Khóa'}</b></div><div class="detail-item"><span>Gần nhất</span><b>${esc(u.last)}</b></div></div></div><button class="btn gold" id="editUserInside">${icon('pencil')} Sửa tài khoản</button>`);setTimeout(()=>$('#editUserInside')?.addEventListener('click',()=>{closeDrawer();modal('Sửa tài khoản',userForm(u));bindUserForm(u.id)}),0)});
  $$('.close-task').forEach(b=>b.onclick=()=>{const x=S.ops.tasks.find(t=>t.id===b.dataset.id);if(x){x.status=x.status==='done'?'open':'done';saveOps();renderChrome();render();toast('Đã cập nhật trạng thái công việc.')}});
  $('#newTask')?.addEventListener('click',()=>modal('Thêm công việc',`<div class="form-grid"><div class="field full"><label>Tên việc</label><input id="taskTitle"></div><div class="field full"><label>Chi tiết</label><textarea id="taskDetail"></textarea></div><div class="field"><label>Mức độ</label><select id="taskLevel"><option value="high">Khẩn</option><option value="medium">Theo dõi</option></select></div><div class="field"><label>Phụ trách</label><input id="taskOwner" value="Điều hành"></div></div><div class="form-actions"><button class="btn" id="cancelTask">Hủy</button><button class="btn gold" id="saveTask">Lưu</button></div>`));
  setTimeout(()=>{if($('#cancelTask'))$('#cancelTask').onclick=closeModal;if($('#saveTask'))$('#saveTask').onclick=()=>{const title=$('#taskTitle').value.trim();if(!title)return toast('Cần nhập tên việc.');S.ops.tasks.unshift({id:'TSK-'+Date.now(),level:$('#taskLevel').value,title,detail:$('#taskDetail').value.trim(),owner:$('#taskOwner').value.trim()||'Điều hành',status:'open'});saveOps();closeModal();renderChrome();render();toast('Đã thêm công việc.')}},0);
  $('#newTour')?.addEventListener('click',()=>toast('Luồng tạo tour sẽ mở cùng booking form trong bước tiếp theo.'));
}
function quickCreate(){modal('Tạo nhanh',`<div class="feature-grid" style="grid-template-columns:repeat(2,1fr);margin:0"><button class="feature-card" data-quick="tour" style="text-align:left;border:1px solid var(--line)"><h3>＋ Tour / Booking</h3><p>Tạo tour và booking ngay trong dashboard.</p></button><button class="feature-card" data-quick="task" style="text-align:left;border:1px solid var(--line)"><h3>＋ Công việc</h3><p>Giao việc hoặc tạo exception cần xử lý.</p></button><button class="feature-card" data-quick="customer" style="text-align:left;border:1px solid var(--line)"><h3>＋ Khách hàng</h3><p>Tạo hồ sơ khách / đoàn.</p></button>${can('*')?`<button class="feature-card" data-quick="user" style="text-align:left;border:1px solid var(--line)"><h3>＋ Tài khoản</h3><p>Tạo user và gán vai trò.</p></button>`:''}</div>`);setTimeout(()=>{$$('[data-quick]').forEach(b=>b.onclick=()=>{const q=b.dataset.quick;closeModal();if(q==='task'){setView('tasks');setTimeout(()=>$('#newTask')?.click(),0)}else if(q==='user'){setView('accounts');setTimeout(()=>$('#newUser')?.click(),0)}else if(q==='tour'){setView('tours');setTimeout(()=>$('#newTour')?.click(),0)}else toast('Luồng này sẽ được bổ sung vào form nghiệp vụ.')} )},0)}
function profileMenu(){modal('Tài khoản',`<div class="drawer-card"><div style="display:flex;align-items:center;gap:10px"><div class="avatar" style="width:42px;height:42px">${initials(S.user.name)}</div><div><b>${esc(S.user.name)}</b><div style="font-size:8px;color:var(--muted);margin-top:3px">${esc(ROLE_META[S.user.role]?.label||S.user.role)}</div></div></div></div><div class="field"><label>Chuyển tài khoản preview</label><select id="switchUser">${S.users.filter(u=>u.status==='active').map(u=>`<option value="${u.id}" ${u.id===S.user.id?'selected':''}>${esc(u.name)} - ${esc(ROLE_META[u.role]?.label||u.role)}</option>`).join('')}</select></div><div class="security-note">Chuyển role này chỉ để QA giao diện quyền trên GitHub Pages. Không phải đăng nhập bảo mật production.</div><div class="form-actions"><button class="btn" id="profileClose">Đóng</button><button class="btn gold" id="switchUserBtn">Chuyển</button></div>`);setTimeout(()=>{$('#profileClose').onclick=closeModal;$('#switchUserBtn').onclick=()=>{const id=$('#switchUser').value;const u=S.users.find(x=>x.id===id);if(u){S.user=u;localStorage.setItem(sessionKey,u.id);closeModal();if(!can(S.view))S.view=can('today')?'today':'overview';renderChrome();render();toast(`Đang xem quyền ${ROLE_META[u.role]?.label||u.role}`)}}},0)}
function globalBindings(){
  $('#quickCreate').onclick=quickCreate;$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))closeModal()};$('#drawerClose').onclick=closeDrawer;$('#drawerBackdrop').onclick=closeDrawer;$('#profileButton').onclick=profileMenu;$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#mobileMore').onclick=()=>$('#sidebar').classList.add('open');
  $('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.trim().toLowerCase();if(!q)return;const t=S.ops.tours.find(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(q)));if(t)tourDrawer(t);else toast('Chưa tìm thấy trong dữ liệu nội bộ hiện tại.')}});
  document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}if(!e.metaKey&&!e.ctrlKey&&!e.altKey&&e.key.toLowerCase()==='n'&&['INPUT','TEXTAREA','SELECT'].indexOf(document.activeElement.tagName)<0)quickCreate();if(e.key==='Escape'){closeModal();closeDrawer();$('#sidebar').classList.remove('open')}});
}
function clock(){const d=new Date();$('#clockText').textContent=tm(d)+' (GMT+7)';$('#dateText').textContent=new Intl.DateTimeFormat('vi-VN',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
function init(){initUser();globalBindings();clock();setInterval(clock,30000);renderChrome();render();syncUpstreams();setInterval(syncUpstreams,C.refreshMs||120000);refreshIcons()}
init();
})();
