(()=>{'use strict';
const C=window.JOTRIP_CONFIG||{},OPS='jotrip-ops-v2',USERS='jotrip-ops-users-v1',SESSION='jotrip-ops-session-v1',DOMAIN='jotrip-ops-domain-v1',LOCK='jotrip-preview-locked-v1';
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const icon=n=>`<i data-lucide="${n}"></i>`,json=(k,d={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||d}catch{return d}},age=t=>{let x=Date.parse(t);return Number.isFinite(x)?Math.max(0,Math.round((Date.now()-x)/60000)):null};
let live={weather:null,airport:null};
function currentUser(){const us=json(USERS,[]),id=localStorage.getItem(SESSION);return us.find(x=>x.id===id)||us[0]||{name:'User',role:'viewer'}}
function ext(){return Object.assign({},window.JOTRIP_EXT_SEED||{},json(DOMAIN,{}))}
function freshness(t,limit){let a=age(t);return a==null?['MISSING','missing','-']:a<=limit?['LIVE','live',a<60?`${a}m`:`${Math.round(a/60)}h`]:['STALE','stale',a<60?`${a}m`:`${Math.round(a/60)}h`]}
function repoRoot(branch){return `https://raw.githubusercontent.com/${C.repo||'kenzuko/Jotrip-Lab'}/${branch||'main'}`}
async function get(url){try{let r=await fetch(url+'?v='+Date.now(),{cache:'no-store'});return r.ok?await r.json():null}catch{return null}}
async function syncMini(){const [w,a]=await Promise.all([get(`${repoRoot(C.weatherBranch)}/weather/dashboard-data.json`),get(`${repoRoot(C.airportBranch)}/data/sunairport/latest.json`)]);if(w)live.weather=w;if(a)live.airport=a;enhance()}
function go(v){const b=$(`.nav-item[data-view="${v}"]`)||$(`#mobileDock [data-view="${v}"]`);if(b)b.click()}
function commandHTML(){const o=json(OPS,{tours:[],tasks:[]}),t=o.tours||[],tasks=o.tasks||[],d=ext(),bookings=d.bookings||[];const open=tasks.filter(x=>x.status==='open'),hi=open.filter(x=>x.level==='high'),issues=t.filter(x=>x.issue),guests=t.reduce((a,x)=>a+(+x.guests||0),0),ready=t.filter(x=>+x.readiness===100).length;const next=t.filter(x=>x.status!=='Đang chạy').slice(0,3);const ex=[...hi.map(x=>({title:x.title,meta:x.owner||'Điều hành',high:true})),...issues.map(x=>({title:`${x.id} · ${x.issue}`,meta:`${x.time} · ${x.guests||0} khách`,high:false}))].slice(0,3);const wf=freshness(live.weather?.generated_at||live.weather?.created_at,C.staleMinutes?.weather||180),af=freshness(live.airport?.collected_at_vn||live.airport?.collected_at,C.staleMinutes?.airport||30);return `<section class="command-v3" id="commandV3"><article class="cmd-hero"><div class="cmd-kicker"><span class="cmd-live-dot"></span>JOTRIP OPERATIONS · LIVE DESK</div><h2>${hi.length?`${hi.length} việc cần xử lý trước`:'Ca vận hành đang trong tầm kiểm soát'}</h2><p>${issues.length?`${issues.length} tour đang có issue. Ưu tiên xử lý exception rồi mới đọc phần còn lại.`:`Không có exception lớn trong dữ liệu nội bộ hiện tại. Tiếp tục theo dõi Weather, Airport và readiness.`}</p><div class="cmd-metrics"><div class="cmd-metric"><b>${t.length}</b><span>tour hôm nay</span></div><div class="cmd-metric"><b>${guests}</b><span>khách</span></div><div class="cmd-metric"><b>${ready}/${t.length||0}</b><span>ready 100%</span></div><div class="cmd-metric"><b>${bookings.length}</b><span>booking đang quản lý</span></div></div></article><article class="cmd-card"><div class="cmd-card-head">${icon('siren')}<b>Exception queue</b><small>${ex.length} ưu tiên</small></div><div class="exception-mini">${ex.length?ex.map(x=>`<div class="exception-mini-row ${x.high?'high':''}"><span class="sev"></span><div><b>${esc(x.title)}</b><small>${esc(x.meta)}</small></div><em>→</em></div>`).join(''):`<div class="exception-mini-row"><span class="sev" style="background:#24aa70"></span><div><b>Không có việc khẩn</b><small>Tiếp tục theo dõi</small></div><em>✓</em></div>`}</div></article><article class="cmd-card"><div class="cmd-card-head">${icon('radio-tower')}<b>Live intelligence</b><small>read-only</small></div><div class="cmd-source-grid"><div class="cmd-source ${wf[1]}"><span class="status-dot"></span><div><b>Weather & Marine</b><small>${wf[2]} · upstream</small></div><span>${wf[0]}</span></div><div class="cmd-source ${af[1]}"><span class="status-dot"></span><div><b>Airport Live</b><small>${af[2]} · upstream</small></div><span>${af[0]}</span></div><div class="cmd-source live"><span class="status-dot"></span><div><b>Internal operations</b><small>${open.length} việc mở · ${next.length} tour sắp chạy</small></div><span>LOCAL</span></div></div></article></section>`}
function ribbonHTML(){const u=currentUser();return `<div class="today-v3-ribbon"><span class="pill">${esc(u.name)} · ${esc(u.role)}</span><span>Exception-first</span><span>Weather/Airport read-only</span><span class="spacer"></span><span>⌘K tìm nhanh</span><span>N tạo nhanh</span></div>`}
function enhance(){const root=$('#pageRoot');if(!root)return;const h=root.querySelector('h1')?.textContent?.trim()||'';const target=h==='Điều hành hôm nay'||h==='Tổng quan JoTrip';root.classList.toggle('v3-ready',target);if(target&&!$('#commandV3',root)){const sb=root.querySelector('.source-banner');if(sb)sb.insertAdjacentHTML('afterend',commandHTML()+ribbonHTML());else root.insertAdjacentHTML('afterbegin',commandHTML()+ribbonHTML());window.lucide?.createIcons?.({'stroke-width':1.8})}updateFieldRail(h)}
function updateFieldRail(h){let rail=$('#fieldRail');if(!rail){rail=document.createElement('div');rail.id='fieldRail';rail.className='field-rail';document.body.appendChild(rail)}const show=['Điều hành hôm nay','Tour & Booking','Việc cần làm','Tổng quan JoTrip'].includes(h);rail.style.display=show?'':'none';const u=currentUser(),guide=u.role==='guide';rail.innerHTML=guide?`<button data-go="tours">${icon('calendar-check')}<span>Tour tôi</span></button><button class="urgent" data-go="tasks">${icon('triangle-alert')}<span>Cảnh báo</span></button><button data-go="weather">${icon('cloud-sun')}<span>Weather</span></button><button data-go="airport">${icon('plane')}<span>Airport</span></button>`:`<button data-go="today">${icon('activity')}<span>Điều hành</span></button><button class="urgent" data-go="tasks">${icon('triangle-alert')}<span>Việc gấp</span></button><button data-go="tours">${icon('calendar-days')}<span>Tour</span></button><button data-go="weather">${icon('cloud-sun')}<span>Biển</span></button>`;rail.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));window.lucide?.createIcons?.({'stroke-width':1.8})}
function closePop(){$('#profilePop')?.remove()}
function showProfile(){closePop();const u=currentUser(),admin=u.role==='admin';const p=document.createElement('div');p.id='profilePop';p.className='profile-pop';p.innerHTML=`<div class="profile-pop-head"><b>${esc(u.name)}</b><small>${esc(u.email||'Tài khoản nội bộ')} · ${esc(u.role)}</small></div><div class="profile-pop-list"><button data-profile-action="switch">${icon('users-round')}<span>Đổi tài khoản preview</span><em class="auth-preview-tag">PREVIEW</em></button>${admin?`<button data-profile-action="accounts">${icon('shield-check')}<span>Tài khoản & phân quyền</span></button>`:''}<button data-profile-action="sync">${icon('refresh-cw')}<span>Tải lại dữ liệu live</span></button><button data-profile-action="lock">${icon('lock-keyhole')}<span>Khoá màn hình preview</span></button></div>`;document.body.appendChild(p);p.querySelector('[data-profile-action="switch"]').onclick=()=>showLogin();p.querySelector('[data-profile-action="accounts"]')?.addEventListener('click',()=>{closePop();go('accounts')});p.querySelector('[data-profile-action="sync"]').onclick=()=>{closePop();syncMini()};p.querySelector('[data-profile-action="lock"]').onclick=()=>{localStorage.setItem(LOCK,'1');closePop();showLogin()};window.lucide?.createIcons?.({'stroke-width':1.8})}
function showLogin(){closePop();$('#loginPreview')?.remove();const us=json(USERS,[]),wrap=document.createElement('div');wrap.id='loginPreview';wrap.className='login-preview';wrap.innerHTML=`<div class="login-card"><img src="./brand-logo.svg" class="login-logo" alt="JoTrip"><h1>JoTrip Operations</h1><p>Chọn tài khoản để kiểm tra giao diện theo vai trò. Đây là màn preview, chưa thay thế Supabase Auth production.</p><div class="login-users">${us.filter(x=>x.status!=='disabled').map(u=>`<button class="login-user" data-user="${esc(u.id)}"><div class="avatar">${esc(String(u.name).split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase())}</div><div><b>${esc(u.name)}</b><small>${esc(u.role)} · ${esc(u.scope||'')}</small></div>${icon('arrow-right')}</button>`).join('')}</div><div class="login-note"><b>Production:</b> đăng nhập thật sẽ bật khi Supabase URL/key được cấu hình. Quyền dữ liệu phải do RLS enforce.</div>${localStorage.getItem(LOCK)!=='1'?`<button class="lock-link" id="cancelPreviewLogin">Đóng màn preview</button>`:''}</div>`;document.body.appendChild(wrap);wrap.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{localStorage.setItem(SESSION,b.dataset.user);localStorage.removeItem(LOCK);location.reload()});wrap.querySelector('#cancelPreviewLogin')?.addEventListener('click',()=>wrap.remove());window.lucide?.createIcons?.({'stroke-width':1.8})}
function bind(){const root=$('#pageRoot');if(root){new MutationObserver(()=>requestAnimationFrame(enhance)).observe(root,{childList:true,subtree:false});enhance()}const profile=$('#profileButton');if(profile)profile.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();$('#profilePop')?closePop():showProfile()},true);document.addEventListener('click',e=>{if($('#profilePop')&&!e.target.closest('#profilePop')&&!e.target.closest('#profileButton'))closePop()});if(localStorage.getItem(LOCK)==='1')showLogin()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();syncMini();setInterval(syncMini,Math.max(120000,C.refreshMs||120000));
})();