(()=>{
'use strict';
const C=window.JOTRIP_CONFIG||{};
const SEED=window.JOTRIP_EXT_SEED||{};
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const e=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const ic=n=>`<i data-lucide="${n}"></i>`;
const cash=n=>Number(n||0).toLocaleString('vi-VN')+'đ';
const ini=n=>String(n||'').split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase();
const clone=o=>JSON.parse(JSON.stringify(o||{}));
const now=()=>new Date();
const tm=d=>new Intl.DateTimeFormat('vi-VN',{hour:'2-digit',minute:'2-digit',hour12:false}).format(d);
const dt=d=>new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);
const age=t=>{const x=Date.parse(t);return Number.isFinite(x)?Math.max(0,Math.round((Date.now()-x)/60000)):null};
const ageText=a=>a==null?'-':a<60?`${a} phút`:`${Math.round(a/60)} giờ`;
const fresh=(t,l)=>{const a=age(t);return a==null?['MISSING','danger',a]:a<=l?['LIVE','ok',a]:['STALE','warn',a]};
const readJSON=(k,f)=>{try{return Object.assign(clone(f),JSON.parse(localStorage.getItem(k)||'{}'))}catch{return clone(f)}};

const defaultOps={
 tours:[
  {id:'JT-ISL-001',time:'07:00',name:'3 đảo',guests:18,host:'Minh / Hằng',vehicle:'Cano 01',readiness:100,status:'Đang chạy',issue:'',nation:'Việt'},
  {id:'JT-PRV-012',time:'08:30',name:'Private Island Day',guests:8,host:'Tùng / Quân',vehicle:'Cano 03',readiness:80,status:'Sắp chạy',issue:'Thiếu xe',nation:'Hàn'},
  {id:'JT-CITY-021',time:'09:00',name:'City & Sunset Town',guests:24,host:'Lan / Phương',vehicle:'Xe 07',readiness:100,status:'Đang chạy',issue:'',nation:'Khác'},
  {id:'JT-FISH-005',time:'13:00',name:'Câu cá lớn',guests:6,host:'Nam / Ken',vehicle:'Cano 02',readiness:60,status:'Sắp chạy',issue:'Theo dõi biển',nation:'Việt'},
  {id:'JT-ISL-018',time:'14:00',name:'3 đảo Nam',guests:20,host:'Huy / Thảo',vehicle:'Cano 04',readiness:100,status:'Sắp chạy',issue:'',nation:'Hàn'},
  {id:'JT-SUN-007',time:'16:00',name:'Sunset Town & cáp treo',guests:28,host:'Hoàng / Linh',vehicle:'Xe 15',readiness:90,status:'Sắp chạy',issue:'',nation:'Khác'},
  {id:'JT-NIGHT-003',time:'17:30',name:'Night Fishing',guests:6,host:'Nam / Quân',vehicle:'Cano 05',readiness:100,status:'Sắp chạy',issue:'',nation:'Việt'}
 ],
 tasks:[
  {id:'TSK-001',level:'high',title:'Xác nhận phương án biển JT-FISH-005',detail:'Theo dõi cửa vận hành và xác nhận với tài công.',owner:'Ken Anh',status:'open'},
  {id:'TSK-002',level:'high',title:'Thiếu xe cho JT-PRV-012',detail:'Cần xác nhận phương tiện trước giờ đón.',owner:'Điều hành',status:'open'},
  {id:'TSK-003',level:'medium',title:'Rà chuyến bay đoàn Hàn',detail:'Đối chiếu Airport Live trước giờ đón.',owner:'Lan Anh',status:'open'}
 ]
};
const defaultUsers=[
 {id:'USR-001',name:'Ken Anh',email:'admin@jotrip.local',role:'admin',status:'active',scope:'Toàn hệ thống',last:'Hiện tại'},
 {id:'USR-002',name:'Lan Anh',email:'lan@jotrip.local',role:'ops',status:'active',scope:'Phú Quốc',last:'14 phút trước'},
 {id:'USR-003',name:'Minh Quân',email:'minh@jotrip.local',role:'sales',status:'active',scope:'Booking & khách',last:'1 giờ trước'},
 {id:'USR-004',name:'Nam',email:'nam@jotrip.local',role:'guide',status:'active',scope:'Tour được giao',last:'32 phút trước'}
];
const D=readJSON('jotrip-ops-domain-v1',SEED), O=readJSON('jotrip-ops-v2',defaultOps), U=readJSON('jotrip-ops-users-v1',defaultUsers);
if(!Array.isArray(O.tours))O.tours=defaultOps.tours;if(!Array.isArray(O.tasks))O.tasks=defaultOps.tasks;
['bookings','customers','partners','people','ferries','handover'].forEach(k=>{if(!Array.isArray(D[k]))D[k]=clone(SEED[k]||[])});

const state={screen:'command',preview:'desktop',weather:null,aqi:null,tide:null,airport:null,airportHealth:null};
const SCREEN_META=[
 ['CORE','command','Command Center','layout-dashboard','Bàn điều hành tổng hợp','Ưu tiên exception, readiness, live source và việc cần xử lý trong 5 giây.',['Hierarchy đầu trang','Mật độ thông tin','Mức nổi của exception']],
 ['CORE','today','Điều hành hôm nay','activity','Timeline theo giờ','Nhìn được tour, nguồn lực và biến động theo giờ trong ngày.',['Timeline có dễ scan không','Tỷ lệ bảng/cảnh báo','Dùng trên màn 13-14 inch']],
 ['CORE','exceptions','Exception Inbox','triangle-alert','Việc lệch chuẩn','Gom mọi vấn đề cần con người xử lý trước.',['Có đủ ưu tiên không','Nút hành động có rõ không','Có nên thêm SLA']],
 ['TOUR','tour-board','Tour Board','calendar-days','Danh sách tour','Quản lý tour theo trạng thái, readiness và issue.',['Dense table hay card','Filter trạng thái','Readiness trực quan']],
 ['TOUR','tour-detail','Tour Detail','route','Chi tiết tour','Một màn xử lý tour từ khách, xe, cano, host đến checklist.',['Checklist 8 mắt xích','Split view','Action đặt ở đâu']],
 ['TOUR','booking-board','Booking Board','notebook-tabs','Booking tổng','Theo dõi booking, pax, payment, source và owner.',['Payment states','Booking source','Tìm kiếm/filter']],
 ['TOUR','booking-detail','Booking Detail','receipt-text','Chi tiết booking','Hồ sơ booking, khách, thanh toán, lịch sử và dịch vụ.',['Đủ thông tin để xử lý chưa','Payment timeline','Cross-link khách/tour']],
 ['CRM','customers','Khách hàng','users','Customer directory','Danh sách khách và phân khúc phục vụ.',['Thông tin nào nên ẩn','Lifetime value','Search nhanh']],
 ['CRM','customer-detail','Customer Profile','contact-round','Hồ sơ khách','Lịch sử booking, sở thích và ghi chú phục vụ.',['Privacy fields','Service notes','Lịch sử hoạt động']],
 ['CRM','partners','Đối tác','handshake','Partner network','Năng lực, xác nhận và thời gian phản hồi của đối tác.',['Card vs table','Xác nhận dịch vụ','Năng lực còn trống']],
 ['CRM','partner-detail','Partner Profile','building-2','Hồ sơ đối tác','Năng lực, SLA, liên hệ, lịch sử giao việc.',['SLA','Capacity','Rating nội bộ']],
 ['OPS','resources','Resource Planner','gantt-chart-square','Xe/cano/host','Phân bổ nguồn lực và phát hiện xung đột.',['Timeline nguồn lực','Conflict highlighting','Drag/drop sau này']],
 ['OPS','people','Nhân sự & roster','briefcase-business','Ca làm','Theo dõi ca, trạng thái hiện trường và phân công.',['Role visibility','Mobile field mode','Bàn giao']],
 ['OPS','person-detail','Staff / Host Detail','badge','Chi tiết nhân sự','Tour được giao, ca, checklist và lịch sử hoạt động.',['Phù hợp HDV không','Action gọi/nhắn','Phạm vi quyền']],
 ['OPS','handover','Bàn giao ca','clipboard-check','Shift handover','Chuyển việc mở và exception sang ca kế tiếp.',['Ngắn gọn nhưng đủ','Ai nhận việc','Timestamp']],
 ['LIVE','airport','Airport Operations','plane','Airport upstream','Đọc Airport Live, ưu tiên chuyến có tác động vận hành.',['Không duplicate trang Airport','Delay impact','Freshness']],
 ['LIVE','sea','Tàu & phà','ship','Sea transport','Manual verification trước khi có nguồn chuyên biệt đáng tin.',['Verified vs unknown','Không suy diễn','Phiếu xác nhận']],
 ['LIVE','weather','Weather & Marine','cloud-sun','Weather upstream','Đọc snapshot Weather Lab, AQI và triều, không sửa decision logic.',['GO/WATCH placement','AQI/triều','Source freshness']],
 ['LIVE','map','Bản đồ vận hành','map','Operational map','Không gian hoá hub, tour, airport và điều kiện.',['Map có cần ở trang chính','Layer controls','Mobile']],
 ['SYSTEM','data','Data Health','database','Source health','Theo dõi LIVE/STALE/MISSING và contract của từng nguồn.',['Freshness thresholds','Schema/version','Alert khi stale']],
 ['SYSTEM','reports','Báo cáo','chart-no-axes-combined','Ops reports','Tổng hợp ca/ngày cho quản lý và bàn giao.',['Không biến thành BI nặng','Chỉ số hữu dụng','Export']],
 ['SYSTEM','accounts','Tài khoản & quyền','shield-check','RBAC','Quản lý user, role và phạm vi truy cập.',['Role đủ chưa','Scope theo tour/đơn vị','Admin UX']],
 ['SYSTEM','settings','Cài đặt','settings-2','System settings','Kết nối, hiển thị, freshness và policy.',['Cái gì admin được sửa','Không cho sửa upstream','Audit']],
 ['MOBILE','field','Mobile Field Mode','smartphone','Field operations','Màn điện thoại cho host/HDV thao tác 1-2 chạm.',['Ưu tiên việc của tôi','Call/message actions','Offline sau này']]
];
const screenById=id=>SCREEN_META.find(x=>x[1]===id)||SCREEN_META[0];
const status=s=>{const x=String(s||'').toLowerCase();let c='';if(x.includes('đã')||x.includes('đang')||x.includes('ready')||x.includes('live')||x.includes('ổn'))c='ok';else if(x.includes('chờ')||x.includes('theo')||x.includes('stale')||x.includes('sắp')||x.includes('watch'))c='warn';else if(x.includes('thiếu')||x.includes('hủy')||x.includes('missing')||x.includes('khẩn'))c='danger';return `<span class="tag ${c}">${e(s||'-')}</span>`};
const sourceRibbon=()=>{const w=fresh(state.weather?.generated_at||state.weather?.created_at,C.staleMinutes?.weather||180),a=fresh(state.airport?.collected_at_vn||state.airport?.collected_at,C.staleMinutes?.airport||30);return `<div class="source-ribbon"><span class="dot ${w[1]}"></span><b>Weather ${w[0]}</b><span>${ageText(w[2])}</span><span class="dot ${a[1]}"></span><b>Airport ${a[0]}</b><span>${ageText(a[2])}</span><span class="push"></span><span class="readonly">READ ONLY UPSTREAM</span></div>`};
const head=(title,sub,actions='')=>`<div class="screen-head"><div><h1>${e(title)}</h1><p>${e(sub)}</p></div>${actions?`<div class="screen-actions">${actions}</div>`:''}</div>`;
const stat=(icon,val,label,sub,cls='')=>`<article class="stat ${cls}"><div class="ico">${ic(icon)}</div><div><strong>${e(val)}</strong><b>${e(label)}</b><small>${e(sub)}</small></div></article>`;
const panel=(title,body,extra='')=>`<section class="panel"><div class="panel-head"><h3>${e(title)}</h3>${extra}</div>${body}</section>`;
const tour=id=>O.tours.find(x=>x.id===id)||O.tours[0];
const booking=id=>(D.bookings||[]).find(x=>x.id===id)||(D.bookings||[])[0]||{};
const customer=id=>(D.customers||[]).find(x=>x.id===id)||(D.customers||[])[0]||{};
const partner=id=>(D.partners||[]).find(x=>x.id===id)||(D.partners||[])[0]||{};
const person=id=>(D.people||[]).find(x=>x.id===id)||(D.people||[])[0]||{};

function exceptionsList(){
 const xs=O.tasks.filter(x=>x.status!=='done').map(x=>({title:x.title,detail:x.detail,owner:x.owner,sev:x.level==='high'?'red':'',time:x.level==='high'?'Cần xử lý':'Theo dõi'}));
 O.tours.filter(x=>x.issue).forEach(x=>xs.push({title:`${x.id} · ${x.issue}`,detail:`${x.name} · ${x.time} · ${x.guests} khách`,owner:x.host,sev:'red',time:'Tour'}));
 return xs;
}
function command(){const open=O.tasks.filter(x=>x.status!=='done').length,issues=O.tours.filter(x=>x.issue).length,total=O.tours.reduce((s,x)=>s+(x.guests||0),0),ready=O.tours.filter(x=>x.readiness===100).length;return `${sourceRibbon()}${head('JoTrip Command Center','Exception-first · internal operations · '+dt(now()),`<button class="btn">${ic('filter')} Bộ lọc</button><button class="btn gold">${ic('plus')} Tạo nhanh</button>`)}<div class="hero-brief"><article class="hero-card"><small>SHIFT BRIEF · ${tm(now())}</small><h2>${O.tours.length} tour · ${total} khách · ${open} việc mở</h2><p>${issues} tour có exception. Weather và Airport chỉ đọc snapshot upstream mới nhất.</p></article><article class="mini-signal alert"><strong>${exceptionsList().filter(x=>x.sev==='red').length}</strong><b>Cần xử lý ngay</b><small>high priority</small></article><article class="mini-signal"><strong>${O.tours.filter(x=>x.status==='Sắp chạy').length}</strong><b>Sắp chạy</b><small>trong ngày</small></article><article class="mini-signal ok"><strong>${ready}</strong><b>Ready 100%</b><small>đủ checklist</small></article></div><div class="grid2"><div class="stack">${panel('Tour đang chạy & sắp chạy',`<div class="dense">${O.tours.slice(0,6).map(x=>`<div class="dense-row"><div class="row-avatar">${x.readiness}%</div><div><b>${e(x.time)} · ${e(x.id)} · ${e(x.name)}</b><p>${x.guests} khách · ${e(x.host)} · ${e(x.vehicle)}</p></div><div class="right">${status(x.issue?'Theo dõi':x.status)}<strong>${e(x.issue||'Ready')}</strong></div></div>`).join('')}</div>`,`<span class="push"></span><span class="eyebrow">TODAY</span>`)}${panel('Booking gần nhất',`<div class="panel-body"><table class="table"><thead><tr><th>Booking</th><th>Khách</th><th>Tour</th><th>Pax</th><th>Payment</th></tr></thead><tbody>${(D.bookings||[]).slice(0,4).map(x=>`<tr><td><b>${e(x.id)}</b></td><td>${e(x.customer)}</td><td>${e(x.tour)}</td><td>${x.pax}</td><td>${status(x.payment)}</td></tr>`).join('')}</tbody></table></div>`)}</div><div class="stack">${panel('Cảnh báo & việc cần xử lý',`<div class="panel-body">${exceptionsList().slice(0,5).map(x=>`<div class="exception ${x.sev}"><div class="rail"></div><div><b>${e(x.title)}</b><p>${e(x.detail)} · ${e(x.owner)}</p></div><time>${e(x.time)}</time></div>`).join('')}</div>`)}${weatherMini()}${panel('Thao tác nhanh',`<div class="quick-grid">${[['Tour','calendar-days'],['Booking','notebook-tabs'],['Khách','users'],['Bàn giao','clipboard-check']].map(x=>`<button class="quick">${ic(x[1])}<span><b>${x[0]}</b><small>Mở workspace</small></span></button>`).join('')}</div>`)}</div></div>`}
function today(){const hours=['06','08','10','12','14','16','18','20'];const rows=[['Tour',['3 đảo','Private Island','','Câu cá','3 đảo Nam','Sunset Town','','Night Fishing']],['Airport',['VJ325','QH1625','','','VJ459','','','']],['Xe',['Xe 01-06','','Xe 07-12','','','','Xe 13-18','']],['Cano',['Cano 01-02','','','Cano 03-04','','','Cano 05-06','']],['HDV/Host',['Nhóm A','','Nhóm B','','Nhóm C','','Nhóm D','']]];return `${sourceRibbon()}${head('Điều hành hôm nay','Timeline vận hành theo giờ - tour, airport, xe, cano, host',`<button class="btn primary">${ic('gantt-chart-square')} Timeline</button><button class="btn">${ic('table-2')} Bảng</button>`)}<div class="stats">${stat('calendar-days',O.tours.length,'Tour trong ngày',`${O.tours.filter(x=>x.status==='Đang chạy').length} đang chạy`)}${stat('users',O.tours.reduce((s,x)=>s+x.guests,0),'Tổng khách','Theo tour')}${stat('triangle-alert',O.tours.filter(x=>x.issue).length,'Tour có vấn đề','Cần xử lý','red')}${stat('route','06:00-22:00','Khung vận hành','Theo lịch hôm nay','blue')}</div>${panel('Timeline vận hành',`<div class="resource-scroll"><div class="resource-board"><div class="head">Nguồn lực</div>${hours.map(h=>`<div class="head">${h}:00</div>`).join('')}${rows.map(r=>`<div class="resource">${r[0]}</div>${r[1].map((v,i)=>`<div class="slot">${v?`<div class="block ${r[0]==='Airport'?'blue':r[0]==='Cano'?'gold':''}">${e(v)}</div>`:''}</div>`).join('')}`).join('')}</div></div>`)}<div class="grid2" style="margin-top:8px">${panel('Tour list',`<div class="panel-body"><table class="table"><thead><tr><th>Giờ</th><th>Tour</th><th>Khách</th><th>Host</th><th>Readiness</th><th>Issue</th></tr></thead><tbody>${O.tours.map(x=>`<tr><td>${e(x.time)}</td><td><b>${e(x.id)}</b> · ${e(x.name)}</td><td>${x.guests}</td><td>${e(x.host)}</td><td><div class="progress ${x.readiness<70?'red':x.readiness<100?'gold':''}"><i style="width:${x.readiness}%"></i></div></td><td>${x.issue?status('Theo dõi'):'-'}</td></tr>`).join('')}</tbody></table></div>`)}${panel('Exception theo giờ',`<div class="panel-body">${exceptionsList().slice(0,4).map(x=>`<div class="exception ${x.sev}"><div class="rail"></div><div><b>${e(x.title)}</b><p>${e(x.detail)}</p></div><time>${e(x.time)}</time></div>`).join('')}</div>`)}</div>`}
function exceptions(){const xs=exceptionsList();return `${head('Exception Inbox','Chỉ hiện việc lệch chuẩn - bình thường thu nhỏ lại',`<button class="btn">${ic('sliders-horizontal')} Bộ lọc</button><button class="btn gold">${ic('plus')} Thêm việc</button>`)}<div class="stats">${stat('siren',xs.filter(x=>x.sev==='red').length,'Khẩn','Cần xử lý ngay','red')}${stat('clock-3',xs.length,'Đang mở','Chưa đóng')}${stat('user-round-check',2,'Đã có owner','Phân công rõ','green')}${stat('timer',32,'Phút','SLA lâu nhất','blue')}</div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Priority queue</h3><span class="push"></span><span class="eyebrow">EXCEPTION FIRST</span></div><div class="panel-body">${xs.map((x,i)=>`<div class="exception ${x.sev}"><div class="rail"></div><div><b>${i+1}. ${e(x.title)}</b><p>${e(x.detail)} · Owner: ${e(x.owner)}</p><div style="margin-top:5px">${status(x.sev==='red'?'KHẨN':'THEO DÕI')}</div></div><time>${e(x.time)}</time></div>`).join('')}</div></section><div class="stack">${panel('SLA theo loại',`<div class="dense"><div class="dense-row"><div class="row-avatar">15m</div><div><b>Tour sắp chạy</b><p>Thiếu xe / host / vé / cano</p></div>${status('Khẩn')}</div><div class="dense-row"><div class="row-avatar">30m</div><div><b>Airport pickup</b><p>Delay / gate / giờ dự kiến</p></div>${status('Theo dõi')}</div><div class="dense-row"><div class="row-avatar">60m</div><div><b>Đối tác</b><p>Chờ xác nhận dịch vụ</p></div>${status('Theo dõi')}</div></div>`)}${panel('Nguyên tắc','<div class="panel-body" style="font-size:7px;line-height:1.6;color:#65777a">Không tự hủy/đổi tour từ cảnh báo thời tiết. Hệ thống chỉ nêu tác động và đề nghị để người điều hành quyết định.</div>')}</div></div>`}
function tourBoard(){return `${head('Tour Board','Dense operational table - scan nhanh theo trạng thái và readiness',`<button class="btn">${ic('filter')} Lọc</button><button class="btn gold">${ic('plus')} Tạo tour</button>`)}<div class="stats">${stat('calendar-days',O.tours.length,'Tour hôm nay','Tất cả trạng thái')}${stat('play',O.tours.filter(x=>x.status==='Đang chạy').length,'Đang chạy','Live ops','green')}${stat('clock-3',O.tours.filter(x=>x.status==='Sắp chạy').length,'Sắp chạy','Cần readiness')}${stat('triangle-alert',O.tours.filter(x=>x.issue).length,'Có issue','Exception','red')}</div><section class="panel table-panel"><div class="panel-head"><h3>Danh sách tour</h3><span class="push"></span><span class="eyebrow">SORT: GIỜ</span></div><div class="panel-body"><table class="table"><thead><tr><th>Giờ</th><th>Mã tour</th><th>Hành trình</th><th>SL khách</th><th>Thị trường</th><th>HDV / Host</th><th>Phương tiện</th><th>Readiness</th><th>Trạng thái</th></tr></thead><tbody>${O.tours.map(x=>`<tr><td>${e(x.time)}</td><td><b>${e(x.id)}</b></td><td>${e(x.name)}</td><td>${x.guests}</td><td>${e(x.nation||'-')}</td><td>${e(x.host)}</td><td>${e(x.vehicle)}</td><td><div class="progress ${x.readiness<70?'red':x.readiness<100?'gold':''}"><i style="width:${x.readiness}%"></i></div><small>${x.readiness}%</small></td><td>${status(x.issue?'Theo dõi':x.status)}</td></tr>`).join('')}</tbody></table></div></section>`}
function tourDetail(){const x=tour('JT-PRV-012');const related=(D.bookings||[]).find(b=>b.tour===x.id);const checks=[['Khách',true,'8/8 confirmed'],['Xe',false,'Thiếu xe'],['Cano',true,x.vehicle],['Host',true,x.host],['Vé',true,'Đủ'],['Đối tác',true,'Đã xác nhận'],['Weather',true,'Theo dõi'],['Payment',true,related?.payment||'Đã cọc']];return `${head(`${x.id} · ${x.name}`,'Tour detail - xử lý một tour mà không cần nhảy qua nhiều module',`<button class="btn">${ic('phone')} Gọi host</button><button class="btn gold">${ic('pencil')} Cập nhật</button>`)}<div class="detail-hero"><div><small>TOUR READINESS</small><h2>${x.time} · ${x.guests} khách · ${e(x.nation)}</h2><p>${e(x.host)} · ${e(x.vehicle)} · ${e(x.issue||'Không có issue')}</p></div><div class="detail-score"><div><b>${x.readiness}</b><span>READY %</span></div></div></div>${panel('Readiness checklist',`<div class="panel-body"><div class="checklist">${checks.map(c=>`<div class="check ${c[1]?'':'warn'}"><i>${c[1]?'✓':'!'}</i><div><b>${c[0]}</b><small>${e(c[2])}</small></div></div>`).join('')}</div></div>`)}<div class="grid2" style="margin-top:8px">${panel('Thông tin vận hành',`<div class="panel-body"><div class="facts"><div class="fact"><small>Giờ khởi hành</small><b>${e(x.time)}</b></div><div class="fact"><small>Khách</small><b>${x.guests}</b></div><div class="fact"><small>Host</small><b>${e(x.host)}</b></div><div class="fact"><small>Phương tiện</small><b>${e(x.vehicle)}</b></div></div></div>`)}${panel('Lịch sử cập nhật',`<div class="timeline"><div class="timeline-item"><span class="node"></span><div><b>Booking đã xác nhận</b><p>${e(related?.id||'BKG')}</p></div><time>08:02</time></div><div class="timeline-item"><span class="node"></span><div><b>Cano xác nhận</b><p>${e(x.vehicle)}</p></div><time>08:08</time></div><div class="timeline-item"><span class="node"></span><div><b>Phát hiện thiếu xe</b><p>Tạo exception cho Điều hành</p></div><time>08:14</time></div></div>`)}</div>`}
function bookingBoard(){const a=D.bookings||[];return `${head('Booking Board','Pax, payment, source và owner trong cùng một bảng',`<button class="btn">${ic('filter')} Lọc</button><button class="btn gold">${ic('plus')} Booking mới</button>`)}<div class="stats">${stat('notebook-tabs',a.length,'Booking','Preview dataset')}${stat('users',a.reduce((s,x)=>s+(x.pax||0),0),'Tổng pax','Theo booking','green')}${stat('wallet-cards',cash(a.reduce((s,x)=>s+(x.value||0),0)),'Booking value','Không phải doanh thu','blue')}${stat('circle-alert',a.filter(x=>String(x.payment).includes('Chờ')||String(x.payment).includes('Còn')).length,'Payment follow-up','Còn phải thu','red')}</div><section class="panel table-panel"><div class="panel-head"><h3>Booking list</h3><span class="push"></span><span class="eyebrow">INTERNAL PREVIEW</span></div><div class="panel-body"><table class="table"><thead><tr><th>Booking</th><th>Khách</th><th>Tour</th><th>Ngày</th><th>Pax</th><th>Source</th><th>Giá trị</th><th>Payment</th><th>Owner</th></tr></thead><tbody>${a.map(x=>`<tr><td><b>${e(x.id)}</b></td><td>${e(x.customer)}</td><td>${e(x.tour)}</td><td>${e(x.date)}</td><td>${x.pax}</td><td>${e(x.source)}</td><td class="money">${cash(x.value)}</td><td>${status(x.payment)}</td><td>${e(x.owner)}</td></tr>`).join('')}</tbody></table></div></section>`}
function bookingDetail(){const b=booking('BKG-260916-01');const c=customer(b.customerId),t=tour(b.tour);return `${head(b.id||'Booking detail',`${b.customer||'-'} · ${b.pax||0} khách · ${b.source||'-'}`,`<button class="btn">${ic('send')} Gửi xác nhận</button><button class="btn gold">${ic('pencil')} Sửa booking</button>`)}<div class="detail-hero"><div><small>BOOKING STATUS</small><h2>${e(b.status||'-')} · ${cash(b.value||0)}</h2><p>${e(b.payment||'-')} · Owner ${e(b.owner||'-')}</p></div><div class="detail-score"><div><b>${b.pax||0}</b><span>PAX</span></div></div></div><div class="grid2 equal">${panel('Khách & liên hệ',`<div class="panel-body"><div class="row-title"><div class="row-avatar">${ini(c.name||b.customer)}</div><div><b>${e(c.name||b.customer)}</b><div style="font-size:6px;color:#7e8d8f">${e(c.nation||'-')} · ${e(c.segment||'-')}</div></div></div><div class="facts" style="margin-top:8px"><div class="fact"><small>Phone</small><b>${e(c.phone||'-')}</b></div><div class="fact"><small>Email</small><b>${e(c.email||'-')}</b></div><div class="fact"><small>Source</small><b>${e(b.source||'-')}</b></div><div class="fact"><small>Owner</small><b>${e(b.owner||'-')}</b></div></div></div>`)}${panel('Tour & dịch vụ',`<div class="panel-body"><div class="row-title"><div class="row-avatar">${t.readiness||0}%</div><div><b>${e(t.id||b.tour)} · ${e(t.name||'-')}</b><div style="font-size:6px;color:#7e8d8f">${e(t.time||'-')} · ${e(t.host||'-')} · ${e(t.vehicle||'-')}</div></div></div><div class="facts" style="margin-top:8px"><div class="fact"><small>Ngày</small><b>${e(b.date||'-')}</b></div><div class="fact"><small>Pax</small><b>${b.pax||0}</b></div><div class="fact"><small>Readiness</small><b>${t.readiness||0}%</b></div><div class="fact"><small>Issue</small><b>${e(t.issue||'Không')}</b></div></div></div>`)}</div>${panel('Payment timeline',`<div class="timeline"><div class="timeline-item"><span class="node"></span><div><b>Booking tạo</b><p>${e(b.source||'-')}</p></div><time>12/09</time></div><div class="timeline-item"><span class="node"></span><div><b>Đã nhận cọc</b><p>Trạng thái: ${e(b.payment||'-')}</p></div><time>13/09</time></div><div class="timeline-item"><span class="node"></span><div><b>Tour xác nhận</b><p>${e(b.status||'-')}</p></div><time>15/09</time></div></div>`)}`}
function customers(){const a=D.customers||[];return `${head('Khách hàng','Customer directory - hồ sơ, phân khúc và lịch sử booking',`<button class="btn">${ic('search')} Tìm</button><button class="btn gold">${ic('user-plus')} Khách mới</button>`)}<div class="stats">${stat('users',a.length,'Hồ sơ khách','Internal preview')}${stat('globe-2',new Set(a.map(x=>x.nation)).size,'Thị trường','Theo quốc tịch','blue')}${stat('sparkles',a.filter(x=>String(x.segment).includes('Luxury')).length,'Private / Luxury','Priority service','green')}${stat('wallet-cards',cash(a.reduce((s,x)=>s+(x.lifetime||0),0)),'Lifetime value','Booking value')}</div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Customer list</h3></div><div class="dense">${a.map(x=>`<div class="dense-row"><div class="row-avatar">${ini(x.name)}</div><div><b>${e(x.name)}</b><p>${e(x.nation)} · ${e(x.segment)} · ${x.bookings} booking</p></div><div class="right"><strong>${cash(x.lifetime)}</strong><small>Gần nhất ${e(x.last)}</small></div></div>`).join('')}</div></section>${panel('Service notes',`<div class="panel-body">${a.map(x=>`<div class="exception"><div class="rail"></div><div><b>${e(x.name)}</b><p>${e(x.note)}</p></div><time>${e(x.segment)}</time></div>`).join('')}</div>`)}</div>`}
function customerDetail(){const c=customer('CUS-001');const bs=(D.bookings||[]).filter(x=>x.customerId===c.id);return `${head(c.name||'Customer Profile',`${c.nation||'-'} · ${c.segment||'-'}`,`<button class="btn">${ic('phone')} Liên hệ</button><button class="btn gold">${ic('plus')} Booking mới</button>`)}<div class="grid2"><div class="stack">${panel('Hồ sơ khách',`<div class="panel-body"><div class="row-title"><div class="row-avatar" style="width:42px;height:42px">${ini(c.name)}</div><div><b style="font-size:10px">${e(c.name)}</b><div style="font-size:6px;color:#7e8d8f">${e(c.nation)} · ${e(c.segment)}</div></div></div><div class="facts" style="margin-top:9px"><div class="fact"><small>Liên hệ</small><b>${e(c.phone)}</b></div><div class="fact"><small>Email</small><b>${e(c.email)}</b></div><div class="fact"><small>Booking</small><b>${c.bookings}</b></div><div class="fact"><small>Lifetime</small><b>${cash(c.lifetime)}</b></div></div></div>`)}${panel('Lịch sử booking',`<div class="panel-body"><table class="table"><thead><tr><th>Booking</th><th>Tour</th><th>Ngày</th><th>Value</th><th>Status</th></tr></thead><tbody>${bs.map(x=>`<tr><td><b>${e(x.id)}</b></td><td>${e(x.tour)}</td><td>${e(x.date)}</td><td>${cash(x.value)}</td><td>${status(x.status)}</td></tr>`).join('')||'<tr><td colspan="5">Chưa có booking trong preview.</td></tr>'}</tbody></table></div>`)}</div><div class="stack">${panel('Service profile',`<div class="panel-body"><div class="eyebrow">GHI CHÚ PHỤC VỤ</div><p style="font-size:8px;line-height:1.6">${e(c.note||'-')}</p><div class="tag">${e(c.segment||'-')}</div></div>`)}${panel('Touchpoints',`<div class="timeline"><div class="timeline-item"><span class="node"></span><div><b>Hotel concierge</b><p>Booking inquiry</p></div><time>12/09</time></div><div class="timeline-item"><span class="node"></span><div><b>Sales xác nhận</b><p>Private Island Day</p></div><time>13/09</time></div><div class="timeline-item"><span class="node"></span><div><b>Pre-trip check</b><p>Đã gửi thông tin đón</p></div><time>15/09</time></div></div>`)}</div></div>`}
function partners(){const a=D.partners||[];return `${head('Đối tác','Năng lực, xác nhận và response time',`<button class="btn gold">${ic('plus')} Thêm đối tác</button>`)}<div class="stats">${stat('handshake',a.length,'Đối tác','Operations list')}${stat('badge-check',a.filter(x=>String(x.confirmed).includes('Đã')).length,'Đã xác nhận','Sẵn sàng','green')}${stat('clock-alert',a.filter(x=>!String(x.confirmed).includes('Đã')).length,'Chờ xác nhận','Follow-up','red')}${stat('timer','5-22m','Response sample','Theo ghi nhận','blue')}</div><div class="grid3">${a.map(x=>`<article class="panel"><div class="panel-body"><div class="row-title"><div class="row-avatar">${ic(x.type.includes('Cano')?'ship':x.type.includes('Xe')?'car-front':'store')}</div><div><b>${e(x.name)}</b><div style="font-size:6px;color:#7d8d8f">${e(x.type)} · ${e(x.contact)}</div></div></div><div style="margin-top:8px">${status(x.confirmed)}</div><div class="facts" style="grid-template-columns:1fr 1fr;margin-top:8px"><div class="fact"><small>Năng lực</small><b>${e(x.capacity)}</b></div><div class="fact"><small>Phản hồi</small><b>${e(x.response)}</b></div></div><p style="font-size:6px;color:#7d8d8f">${e(x.services)} · ${e(x.rating)}</p></div></article>`).join('')}</div>`}
function partnerDetail(){const p=partner('PAR-002');return `${head(p.name||'Partner Profile',`${p.type||'-'} · ${p.contact||'-'}`,`<button class="btn">${ic('phone')} Liên hệ</button><button class="btn gold">${ic('send')} Giao việc</button>`)}<div class="detail-hero"><div><small>PARTNER STATUS</small><h2>${e(p.confirmed||'-')} · ${e(p.capacity||'-')}</h2><p>${e(p.services||'-')} · Response ${e(p.response||'-')}</p></div><div class="detail-score"><div><b>4.8</b><span>INTERNAL</span></div></div></div><div class="grid2 equal">${panel('Năng lực & SLA',`<div class="panel-body"><div class="facts"><div class="fact"><small>Dịch vụ</small><b>${e(p.type)}</b></div><div class="fact"><small>Năng lực</small><b>${e(p.capacity)}</b></div><div class="fact"><small>Response</small><b>${e(p.response)}</b></div><div class="fact"><small>Rating</small><b>${e(p.rating)}</b></div></div></div>`)}${panel('Lịch sử giao việc',`<div class="timeline"><div class="timeline-item"><span class="node"></span><div><b>JT-ISL-001</b><p>Cano 01 · confirmed</p></div><time>Hôm nay</time></div><div class="timeline-item"><span class="node"></span><div><b>JT-PRV-012</b><p>Cano 03 · confirmed</p></div><time>Hôm nay</time></div><div class="timeline-item"><span class="node"></span><div><b>JT-FISH-005</b><p>Cano 02 · watch</p></div><time>13:00</time></div></div>`)}</div>`}
function resources(){const rows=[['Xe 01','JT-ISL-001','Đón khách','','City','',''],['Xe 07','','JT-CITY-021','','','Sunset',''],['Cano 01','JT-ISL-001','','','','',''],['Cano 03','','JT-PRV-012','','','',''],['Host Nam','','','','JT-FISH-005','','Night'],['Host Hằng','JT-ISL-001','','','','','']];const hs=['07','09','11','13','15','17'];return `${head('Resource Planner','Xe, cano, host và xung đột theo giờ',`<button class="btn">${ic('filter')} Loại nguồn lực</button><button class="btn gold">${ic('wand-sparkles')} Auto-check conflict</button>`)}<div class="stats">${stat('car-front',24,'Xe','18 đang dùng')}${stat('ship-wheel',6,'Cano','4 đang dùng','green')}${stat('users-round',18,'HDV / Host','15 đang làm','blue')}${stat('triangle-alert',1,'Conflict','Cần xử lý','red')}</div>${panel('Resource timeline',`<div class="resource-scroll"><div class="resource-board"><div class="head">Nguồn lực</div>${hs.map(h=>`<div class="head">${h}:00</div>`).join('')}${rows.map(r=>`<div class="resource">${r[0]}</div>${r.slice(1).map((v,i)=>`<div class="slot">${v?`<div class="block ${i%3===1?'gold':i%3===2?'blue':''}">${e(v)}</div>`:''}</div>`).join('')}`).join('')}</div></div>`)}<div class="grid2 equal" style="margin-top:8px">${panel('Conflict detected','<div class="panel-body"><div class="exception red"><div class="rail"></div><div><b>Xe 07 overlap 15:30-16:00</b><p>JT-CITY-021 → JT-SUN-007, cần buffer hoặc đổi xe.</p></div><time>30m</time></div></div>')}${panel('Available pool','<div class="panel-body"><div class="tag ok">6 xe trống</div> <div class="tag ok">2 cano trống</div> <div class="tag warn">3 host dự phòng</div></div>')}</div>`}
function people(){const a=D.people||[];return `${head('Nhân sự & roster','Ca làm, trạng thái hiện trường và phân công',`<button class="btn">${ic('calendar')} Xem ca</button><button class="btn gold">${ic('user-plus')} Thêm ca</button>`)}<div class="stats">${stat('users-round',a.length,'Nhân sự hôm nay','Roster preview')}${stat('user-check',a.filter(x=>x.status==='Đang làm').length,'Đang làm','Trong văn phòng','green')}${stat('map-pin',a.filter(x=>String(x.status).includes('hiện trường')).length,'Hiện trường','Đang phục vụ','blue')}${stat('clipboard-list',(D.handover||[]).length,'Bàn giao','Cho ca sau')}</div>${panel('Roster hôm nay',`<div class="panel-body"><table class="table"><thead><tr><th>Nhân sự</th><th>Vai trò</th><th>Ca</th><th>Trạng thái</th><th>Phân công</th></tr></thead><tbody>${a.map(x=>`<tr><td><div class="row-title"><div class="row-avatar">${ini(x.name)}</div><b>${e(x.name)}</b></div></td><td>${e(x.role)}</td><td>${e(x.shift)}</td><td>${status(x.status)}</td><td>${e(x.assignment)}</td></tr>`).join('')}</tbody></table></div>`)}`}
function personDetail(){const p=person('EMP-004');return `${head(p.name||'Staff Detail',`${p.role||'-'} · ${p.status||'-'}`,`<button class="btn">${ic('phone')} Gọi</button><button class="btn gold">${ic('message-circle')} Nhắn</button>`)}<div class="grid2"><div class="stack">${panel('Hồ sơ ca hiện tại',`<div class="panel-body"><div class="row-title"><div class="row-avatar" style="width:46px;height:46px">${ini(p.name)}</div><div><b style="font-size:10px">${e(p.name)}</b><div style="font-size:6px;color:#7e8d8f">${e(p.role)} · ${e(p.status)}</div></div></div><div class="facts" style="margin-top:9px"><div class="fact"><small>Ca</small><b>${e(p.shift)}</b></div><div class="fact"><small>Assignment</small><b>${e(p.assignment)}</b></div><div class="fact"><small>Check-in</small><b>05:02</b></div><div class="fact"><small>Thiết bị</small><b>Mobile</b></div></div></div>`)}${panel('Tour được giao',`<div class="dense"><div class="dense-row"><div class="row-avatar">60%</div><div><b>JT-FISH-005 · Câu cá lớn</b><p>13:00 · 6 khách · Cano 02</p></div>${status('Theo dõi')}</div></div>`)}</div><div class="stack">${panel('Field checklist','<div class="panel-body"><div class="checklist" style="grid-template-columns:1fr 1fr"><div class="check"><i>✓</i><div><b>Khách</b><small>Đủ danh sách</small></div></div><div class="check"><i>✓</i><div><b>Cano</b><small>Cano 02</small></div></div><div class="check warn"><i>!</i><div><b>Weather</b><small>Watch</small></div></div><div class="check"><i>✓</i><div><b>Gear</b><small>Đủ</small></div></div></div></div>')}${panel('Activity',`<div class="timeline"><div class="timeline-item"><span class="node"></span><div><b>Check-in</b><p>An Thới</p></div><time>05:02</time></div><div class="timeline-item"><span class="node"></span><div><b>Xác nhận gear</b><p>Fishing kit</p></div><time>05:18</time></div><div class="timeline-item"><span class="node"></span><div><b>Weather watch</b><p>Đã nhận cảnh báo</p></div><time>10:40</time></div></div>`)}</div></div>`}
function handover(){const h=D.handover||[];return `${head('Bàn giao ca','Việc chưa đóng + exception + trách nhiệm ca kế tiếp',`<button class="btn">${ic('download')} Xuất</button><button class="btn gold">${ic('send')} Gửi ca sau</button>`)}<div class="detail-hero"><div><small>CURRENT SHIFT · 13:00-22:00</small><h2>${h.length} mục cần bàn giao</h2><p>Ca sau: 22:00-06:00 · mọi mục phải có owner hoặc ghi rõ “chưa phân công”.</p></div><div class="detail-score"><div><b>${O.tasks.filter(x=>x.status!=='done').length}</b><span>OPEN</span></div></div></div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Handover checklist</h3></div><div class="panel-body">${h.map((x,i)=>`<div class="exception ${x.level==='watch'?'red':''}"><div class="rail"></div><div><b>${i+1}. ${e(x.title)}</b><p>${e(x.detail)}</p><div style="margin-top:4px">${status(x.level==='watch'?'Theo dõi':'Thông tin')}</div></div><time>Ca sau</time></div>`).join('')}</div></section>${panel('Người nhận ca','<div class="panel-body"><div class="dense-row"><div class="row-avatar">T</div><div><b>Ca tối</b><p>22:00-06:00 · Operations</p></div><div class="right"><strong>2 người</strong><small>Chưa xác nhận</small></div></div><button class="btn primary" style="margin-top:8px">Xác nhận nhận ca</button></div>')}</div>`}
function airport(){const a=state.airport,rs=a?.records||[];const f=fresh(a?.collected_at_vn||a?.collected_at,C.staleMinutes?.airport||30);return `${sourceRibbon()}${head('Airport Operations','Tóm tắt upstream Airport Live - chỉ tập trung tác động vận hành',`<a class="btn primary" href="${e(C.airportWebUrl||'#')}" target="_blank">${ic('external-link')} Mở Airport Live</a>`)}<div class="stats">${stat('plane-landing',a?.counts?.arrivals??rs.filter(x=>x.direction==='arrival').length,'Arrivals','Snapshot hiện tại','green')}${stat('plane-takeoff',a?.counts?.departures??rs.filter(x=>x.direction==='departure').length,'Departures','Snapshot hiện tại','blue')}${stat('clock-alert',rs.filter(x=>String(x.status).toLowerCase().includes('delay')).length,'Delay','Theo source','red')}${stat('database-zap',f[0],'Freshness',ageText(f[2]))}</div><div class="grid2"><section class="panel table-panel"><div class="panel-head"><h3>Flight board</h3><span class="push"></span><span class="readonly">READ ONLY</span></div><div class="panel-body"><table class="table"><thead><tr><th>Loại</th><th>Chuyến</th><th>Hãng</th><th>Nơi đi/đến</th><th>Giờ</th><th>Status</th></tr></thead><tbody>${rs.slice(0,12).map(x=>`<tr><td>${x.direction==='arrival'?'Đến':'Đi'}</td><td><b>${e(x.operating_flight_number||'-')}</b></td><td>${e(x.carrier||'-')}</td><td>${e(x.station||'-')}</td><td>${e(x.scheduled_time||'-')}</td><td>${status(x.status||'-')}</td></tr>`).join('')||'<tr><td colspan="6">Đang chờ Airport snapshot.</td></tr>'}</tbody></table></div></section>${panel('Impact watch',`<div class="panel-body"><div class="exception"><div class="rail"></div><div><b>Đoàn Hàn pickup</b><p>Đối chiếu flight T-90 phút, không tự lấy ETA giả.</p></div><time>Watch</time></div><div class="exception"><div class="rail"></div><div><b>Source freshness</b><p>${f[0]} · ${ageText(f[2])}</p></div><time>${f[0]}</time></div></div>`)}</div>`}
function sea(){const a=D.ferries||[];return `${head('Tàu & phà','Manual verification board - chưa xác minh không được coi là LIVE')}<div class="source-ribbon"><span class="dot warn"></span><b>Không có upstream chuyên biệt đang khóa</b><span>Manual verification</span><span class="push"></span><span class="readonly">NO INFERENCE</span></div><div class="stats">${stat('ship',a.length,'Tuyến theo dõi','Manual board')}${stat('badge-check',a.filter(x=>x.verifiedAt).length,'Đã xác minh','Có timestamp','green')}${stat('circle-dashed',a.filter(x=>!x.verifiedAt).length,'Chưa xác minh','Không kết luận','red')}${stat('file-check-2','Required','Phiếu / nguồn','Khi có')}</div>${panel('Sea transport board',`<div class="panel-body"><table class="table"><thead><tr><th>Tuyến</th><th>Nhà khai thác</th><th>Giờ</th><th>Trạng thái</th><th>Xác minh lúc</th><th>Ghi chú</th></tr></thead><tbody>${a.map(x=>`<tr><td><b>${e(x.route)}</b></td><td>${e(x.operator)}</td><td>${e(x.time)}</td><td>${status(x.state)}</td><td>${x.verifiedAt?tm(new Date(x.verifiedAt)):'-'}</td><td>${e(x.note)}</td></tr>`).join('')}</tbody></table></div>`)}`}
function weatherMini(){const p=state.weather?.points?.duong_dong||{};const a=state.aqi?.points?.duong_dong||{};const t=state.tide?.points?.duong_dong||{};return panel('Dương Đông · điều kiện hiện tại',`<div class="panel-body"><div class="weather-temp">${p.temperature!=null?p.temperature+'°C':'--°C'}</div><div class="weather-metrics"><div><span>Gió</span><b>${p.wind??'-'} km/h</b></div><div><span>Sóng</span><b>${p.wave??'-'} m</b></div><div><span>AQI</span><b>${a.aqi_us??'-'}</b></div><div><span>Triều</span><b>${e(t.trend||'-')}</b></div></div></div>`,`<span class="push"></span><span class="readonly">READ ONLY</span>`) }
function weather(){const p=state.weather?.points||{},aq=state.aqi?.points||{},ti=state.tide?.points||{};const keys=['duong_dong','an_thoi','ganh_dau'];return `${sourceRibbon()}${head('Weather & Marine','Snapshot chuyên sâu từ Weather Lab - dashboard không sửa forecast/decision logic',`<button class="btn primary">${ic('external-link')} Mở Weather Lab</button>`)}<div class="weather-grid">${keys.map(k=>{const z=p[k]||{},a=aq[k]||{},t=ti[k]||{};return `<article class="weather-card"><h4>${e(z.name||({duong_dong:'Dương Đông',an_thoi:'An Thới',ganh_dau:'Gành Dầu'}[k]))}</h4><div class="weather-temp">${z.temperature!=null?z.temperature+'°C':'--°C'}</div><div class="weather-metrics"><div><span>Gió</span><b>${z.wind??'-'} km/h</b></div><div><span>Sóng Hs</span><b>${z.wave??'-'} m</b></div><div><span>Mưa</span><b>${z.rain??'-'} mm</b></div><div><span>AQI</span><b>${a.aqi_us??'-'}</b></div><div><span>Triều</span><b>${e(t.trend||'-')}</b></div></div><div style="margin-top:8px">${status(z.decision||state.weather?.decision||'Chưa phát')}</div></article>`}).join('')}</div><div class="grid2" style="margin-top:8px">${panel('Operational window','<div class="panel-body"><div class="resource-board" style="grid-template-columns:100px repeat(6,1fr);min-width:620px"><div class="head">Khung giờ</div><div class="head">06-08</div><div class="head">08-10</div><div class="head">10-12</div><div class="head">12-14</div><div class="head">14-16</div><div class="head">16-18</div><div class="resource">An Thới</div><div class="slot"><div class="block">GO</div></div><div class="slot"><div class="block">GO</div></div><div class="slot"><div class="block">GO</div></div><div class="slot"><div class="block gold">WATCH</div></div><div class="slot"><div class="block gold">WATCH</div></div><div class="slot"><div class="block">GO</div></div></div></div>')}${panel('Source / decision policy','<div class="panel-body" style="font-size:7px;line-height:1.6;color:#617477">Lab là data plane, Dashboard chỉ đọc output. Nếu thiếu hoặc stale thì hạ trạng thái. Không tự điền 0, không tự sửa quyết định và không biến cảnh báo thành hủy tour.</div>')}</div>`}
function mapView(){return `${head('Bản đồ vận hành','Hub, tour, airport và layer điều kiện trong một không gian',`<button class="btn">${ic('layers')} Layers</button><button class="btn gold">${ic('locate-fixed')} Fit operations</button>`)}<div class="source-ribbon"><span class="dot"></span><b>Điểm vận hành</b><span class="dot warn"></span><b>Hub / Airport</b><span class="push"></span><span class="readonly">MAP PREVIEW</span></div><div class="mini-map"><div class="map-pin" style="left:48%;top:42%"><i></i><b>Dương Đông</b></div><div class="map-pin" style="left:66%;top:70%"><i></i><b>An Thới</b></div><div class="map-pin" style="left:31%;top:20%"><i></i><b>Gành Dầu</b></div><div class="map-pin hub" style="left:56%;top:55%"><i></i><b>PQC Airport</b></div><div class="map-pin" style="left:72%;top:78%"><i></i><b>Hòn Thơm</b></div></div>`}
function dataHealth(){const w=fresh(state.weather?.generated_at||state.weather?.created_at,C.staleMinutes?.weather||180),a=fresh(state.airport?.collected_at_vn||state.airport?.collected_at,C.staleMinutes?.airport||30),q=fresh(state.aqi?.sampled_time,C.staleMinutes?.airQuality||360),t=fresh(state.tide?.generated_at,C.staleMinutes?.tide||180);const rows=[['Weather Lab',state.weather?.completeness!=null?state.weather.completeness+'%':'-',w],['AQI',state.aqi?.status||'-',q],['Triều',state.tide?.status||'-',t],['Airport Live',state.airport?.quality?.passed?'QA PASS':'-',a],['Tour / Booking','LOCAL PREVIEW',['LOCAL','warn',null]]];return `${head('Data Health','LIVE / STALE / MISSING phải tách rõ - không biến missing thành zero',`<button class="btn">${ic('refresh-cw')} Recheck</button>`)}<div class="stats">${stat('database-zap',rows.filter(x=>x[2][0]==='LIVE').length,'LIVE source','Fresh')}${stat('clock-alert',rows.filter(x=>x[2][0]==='STALE').length,'STALE source','Cần chú ý','red')}${stat('circle-help',rows.filter(x=>x[2][0]==='MISSING').length,'MISSING','Không dữ liệu')}${stat('shield-check','0 write','Upstream','Read-only','green')}</div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Source health</h3></div><div class="health-list">${rows.map(x=>`<div class="health-row"><div><b>${e(x[0])}</b><small>${e(x[1])}</small></div><span>${x[2][2]!=null?ageText(x[2][2]):'-'}</span>${status(x[2][0])}</div>`).join('')}</div></section>${panel('Contract policy','<div class="panel-body"><div class="exception"><div class="rail"></div><div><b>Upstream schema changes</b><p>Adapter chỉ đọc field nhận diện được. Thiếu field thì hạ state, không tự bịa giá trị.</p></div><time>LOCK</time></div><div class="exception"><div class="rail"></div><div><b>Last valid snapshot</b><p>Giữ snapshot hợp lệ gần nhất nhưng luôn hiển thị tuổi dữ liệu.</p></div><time>POLICY</time></div></div>')}</div>`}
function reports(){const total=O.tours.reduce((s,x)=>s+x.guests,0),open=O.tasks.filter(x=>x.status!=='done').length,ready=O.tours.filter(x=>x.readiness===100).length;return `${head('Báo cáo & Ops Pulse','Báo cáo gọn cho quản lý và bàn giao - không biến thành BI nặng',`<button class="btn">${ic('download')} CSV</button><button class="btn gold">${ic('clipboard-copy')} Bàn giao</button>`)}<div class="detail-hero"><div><small>OPERATIONS PULSE</small><h2>${O.tours.length} tour · ${total} khách · ${open} việc mở</h2><p>Chỉ báo nội bộ từ readiness và exception. Không phải kết luận an toàn hay KPI tài chính.</p></div><div class="detail-score"><div><b>${Math.round(ready/Math.max(1,O.tours.length)*100)}</b><span>READY INDEX</span></div></div></div><div class="grid3">${panel('Readiness','<div class="panel-body"><div style="font:800 22px Manrope">'+ready+'/'+O.tours.length+'</div><p style="font-size:7px;color:#7f8e90">Tour đạt readiness 100%</p><div class="progress"><i style="width:'+Math.round(ready/O.tours.length*100)+'%"></i></div></div>')}${panel('Exception','<div class="panel-body"><div style="font:800 22px Manrope;color:#d95047">'+open+'</div><p style="font-size:7px;color:#7f8e90">Việc đang mở</p><div class="progress red"><i style="width:'+Math.min(100,open*20)+'%"></i></div></div>')}${panel('Booking value','<div class="panel-body"><div style="font:800 18px Manrope">'+cash((D.bookings||[]).reduce((s,x)=>s+(x.value||0),0))+'</div><p style="font-size:7px;color:#7f8e90">Không phải doanh thu kế toán</p></div>')}</div><div class="grid2" style="margin-top:8px">${panel('Market mix','<div class="panel-body"><table class="table"><tbody><tr><td>Việt Nam</td><td><b>32%</b></td></tr><tr><td>Hàn Quốc</td><td><b>28%</b></td></tr><tr><td>Khác</td><td><b>40%</b></td></tr></tbody></table></div>')}${panel('Open handover',`<div class="panel-body">${(D.handover||[]).map(x=>`<div class="exception"><div class="rail"></div><div><b>${e(x.title)}</b><p>${e(x.detail)}</p></div><time>${e(x.level)}</time></div>`).join('')}</div>`)}</div>`}
function accounts(){const roleMeta={admin:'Administrator',ops:'Điều hành',sales:'Sales & Booking',guide:'HDV / Host',data:'Data / Analyst',viewer:'Chỉ xem'};return `${head('Tài khoản & phân quyền','Role-based access + scope - UI preview trước khi nối Auth/RLS',`<button class="btn gold">${ic('user-plus')} Tạo tài khoản</button>`)}<div class="source-ribbon"><span class="dot warn"></span><b>LOCAL PREVIEW</b><span>UI role simulation</span><span class="push"></span><span class="readonly">BACKEND/RLS REQUIRED</span></div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Người dùng</h3><span class="push"></span><span class="eyebrow">ADMIN ONLY</span></div><div class="dense">${U.map(x=>`<div class="dense-row"><div class="row-avatar">${ini(x.name)}</div><div><b>${e(x.name)}</b><p>${e(x.email)} · ${e(x.scope)}</p></div><div class="right">${status(roleMeta[x.role]||x.role)}<small>${e(x.last)}</small></div></div>`).join('')}</div></section>${panel('Role model','<div class="panel-body"><div class="role-grid"><article class="role-card"><h4>Admin</h4><p>Toàn quyền hệ thống.</p><div class="role-perms"><span>Users</span><span>Settings</span><span>Ops</span></div></article><article class="role-card"><h4>Operations</h4><p>Tour, task, khách, đối tác, bàn giao.</p><div class="role-perms"><span>Write Ops</span><span>Reports</span></div></article><article class="role-card"><h4>Sales</h4><p>Booking, khách, đối tác.</p><div class="role-perms"><span>Booking</span><span>CRM</span></div></article><article class="role-card"><h4>HDV / Host</h4><p>Tour được giao + field update.</p><div class="role-perms"><span>Assigned</span></div></article><article class="role-card"><h4>Data</h4><p>Sources, reports, live intelligence.</p><div class="role-perms"><span>Read data</span></div></article><article class="role-card"><h4>Viewer</h4><p>Chỉ đọc.</p><div class="role-perms"><span>Read</span></div></article></div></div>')}</div>`}
function settings(){return `${head('Cài đặt hệ thống','Chỉ admin - upstream Weather/Airport không cho sửa dữ liệu từ đây')}<div class="settings-grid"><article class="setting-card"><h3>Brand & appearance</h3><p>JoTrip Yellow #FCBC12 · Green #77944C · Forest Ops.</p><div class="setting-row"><span>Compact density</span><span class="toggle on"><i></i></span></div><div class="setting-row"><span>High contrast alerts</span><span class="toggle on"><i></i></span></div></article><article class="setting-card"><h3>Weather upstream</h3><p>${e(C.weatherBranch||'-')} · read-only snapshot.</p><div class="setting-row"><span>Auto refresh</span><span class="toggle on"><i></i></span></div><div class="setting-row"><span>Write access</span><b style="font-size:7px;color:#b4433b">DISABLED</b></div></article><article class="setting-card"><h3>Airport upstream</h3><p>${e(C.airportBranch||'-')} · ${e(C.airportWebUrl||'-')}</p><div class="setting-row"><span>Auto refresh</span><span class="toggle on"><i></i></span></div><div class="setting-row"><span>Write access</span><b style="font-size:7px;color:#b4433b">DISABLED</b></div></article><article class="setting-card"><h3>Freshness policy</h3><p>Weather ${C.staleMinutes?.weather||180} phút · Airport ${C.staleMinutes?.airport||30} phút.</p><div class="setting-row"><span>Show STALE badge</span><span class="toggle on"><i></i></span></div><div class="setting-row"><span>Missing = zero</span><b style="font-size:7px;color:#b4433b">NEVER</b></div></article></div>`}
function field(){const assigned=O.tours.filter(x=>String(x.host).includes('Nam')).slice(0,2);return `${head('Mobile Field Mode','Host / HDV - chỉ việc của tôi và thao tác 1-2 chạm')}<div class="detail-hero"><div><small>HELLO NAM · HOST</small><h2>${assigned.length} tour được giao hôm nay</h2><p>Ưu tiên tour tiếp theo, cảnh báo và contact nhanh.</p></div><div class="detail-score"><div><b>${tm(now())}</b><span>LOCAL</span></div></div></div>${panel('Tour của tôi',`<div class="dense">${assigned.map(x=>`<div class="dense-row"><div class="row-avatar">${x.readiness}%</div><div><b>${e(x.time)} · ${e(x.name)}</b><p>${x.guests} khách · ${e(x.vehicle)}</p></div><div class="right">${status(x.issue?'WATCH':x.status)}</div></div>`).join('')}</div>`)}<div class="grid2 equal" style="margin-top:8px">${panel('Quick actions','<div class="quick-grid"><button class="quick">'+ic('phone')+'<span><b>Gọi điều hành</b><small>1 chạm</small></span></button><button class="quick">'+ic('message-circle')+'<span><b>Nhắn nhóm</b><small>Tour chat</small></span></button><button class="quick">'+ic('map-pin')+'<span><b>Điểm đón</b><small>Mở map</small></span></button><button class="quick">'+ic('circle-check')+'<span><b>Check-in</b><small>Cập nhật</small></span></button></div>')}${panel('Cảnh báo gần nhất','<div class="panel-body"><div class="exception red"><div class="rail"></div><div><b>JT-FISH-005 · Weather WATCH</b><p>Chờ xác nhận cửa biển. Không tự đổi tour.</p></div><time>Now</time></div></div>')}</div>`}

const RENDER={command,today,exceptions,'tour-board':tourBoard,'tour-detail':tourDetail,'booking-board':bookingBoard,'booking-detail':bookingDetail,customers,'customer-detail':customerDetail,partners,'partner-detail':partnerDetail,resources,people,'person-detail':personDetail,handover,airport,sea,weather,map:mapView,data:dataHealth,reports,accounts,settings,field};
function protoNav(){const items=[['Điều hành','command','layout-dashboard'],['Điều hành hôm nay','today','activity'],['Việc cần làm','exceptions','triangle-alert'],['Tour & Booking','tour-board','calendar-days'],['Khách hàng','customers','users'],['Đối tác','partners','handshake'],['Nhân sự','people','briefcase-business'],['Airport Live','airport','plane'],['Tàu & phà','sea','ship'],['Weather & Marine','weather','cloud-sun'],['Bản đồ','map','map'],['Dữ liệu & nguồn','data','database'],['Báo cáo','reports','chart-no-axes-combined'],['Tài khoản','accounts','shield-check']];return `<div class="proto-nav-label">OPERATIONS</div>${items.map(x=>`<div class="proto-nav-item ${state.screen===x[1]?'active':''}" data-proto="${x[1]}">${ic(x[2])}<span>${x[0]}</span>${x[1]==='exceptions'?'<span class="badge">3</span>':''}</div>`).join('')}`}
function mobileBottom(){return [['today','activity','Điều hành'],['tour-board','calendar-days','Tour'],['exceptions','triangle-alert','Cảnh báo'],['airport','plane','Airport'],['field','menu','Thêm']].map(x=>`<button class="${state.screen===x[0]?'active':''}" data-mobile-screen="${x[0]}">${ic(x[1])}<span>${x[2]}</span></button>`).join('')}
function buildNav(filter=''){let out='',last='';SCREEN_META.filter(x=>x[2].toLowerCase().includes(filter.toLowerCase())||x[4].toLowerCase().includes(filter.toLowerCase())).forEach((x,i)=>{if(x[0]!==last){out+=`<div class="nav-section">${x[0]}</div>`;last=x[0]}const num=String(SCREEN_META.indexOf(x)+1).padStart(2,'0');out+=`<button class="screen-link ${state.screen===x[1]?'active':''}" data-screen="${x[1]}"><span class="num">${num}</span><span>${e(x[2])}</span><em>${ic(x[3])}</em></button>`});$('#screenNav').innerHTML=out;}
function notes(){const m=screenById(state.screen);$('#notesTitle').textContent=m[2];$('#notesGoal').textContent=m[5];$('#notesChecks').innerHTML=m[6].map(x=>`<li>${e(x)}</li>`).join('')}
function render(){const meta=screenById(state.screen);$('#currentScreenName').textContent=meta[2];$('#screenCanvas').innerHTML=(RENDER[state.screen]||command)();$('#protoNav').innerHTML=protoNav();$('#mobileBottom').innerHTML=mobileBottom();buildNav($('#screenSearch').value||'');notes();requestAnimationFrame(()=>window.lucide?.createIcons?.({attrs:{'stroke-width':1.8}}));}
function go(id){state.screen=screenById(id)[1];location.hash='screen='+state.screen;render();$('#reviewSidebar').classList.remove('open')}
async function getJSON(url){try{const r=await fetch(url+(url.includes('?')?'&':'?')+'v='+Date.now(),{cache:'no-store'});if(!r.ok)throw 0;return await r.json()}catch{return null}}
async function sync(){const repo=C.repo||'kenzuko/Jotrip-Lab',wb=C.weatherBranch||'main',ab=C.airportBranch||'main',wr=`https://raw.githubusercontent.com/${repo}/${wb}`,ar=`https://raw.githubusercontent.com/${repo}/${ab}`;const [w,q,t,a,h]=await Promise.all([getJSON(`${wr}/weather/dashboard-data.json`),getJSON(`${wr}/weather/air-quality.json`),getJSON(`${wr}/weather/tide.json`),getJSON(`${ar}/data/sunairport/latest.json`),getJSON(`${ar}/data/sunairport/health.json`)]);if(w)state.weather=w;if(q)state.aqi=q;if(t)state.tide=t;if(a)state.airport=a;if(h)state.airportHealth=h;const wf=fresh(state.weather?.generated_at||state.weather?.created_at,C.staleMinutes?.weather||180),af=fresh(state.airport?.collected_at_vn||state.airport?.collected_at,C.staleMinutes?.airport||30);const bad=wf[1]==='danger'||af[1]==='danger'?'danger':wf[1]==='warn'||af[1]==='warn'?'warn':'ok';const d=$('#sourceHealth .health-dot');d.className='health-dot '+bad;$('#sourceHealth b').textContent=bad==='ok'?'Nguồn ổn định':bad==='warn'?'Có nguồn stale':'Có nguồn missing';$('#sourceHealth small').textContent=`Weather ${wf[0]} · Airport ${af[0]}`;$('#protoHealth').textContent=bad==='ok'?'Nguồn ổn định':bad==='warn'?'Có nguồn stale':'Kiểm tra nguồn';$('#protoHealthMeta').textContent=`Weather ${wf[0]} · Airport ${af[0]}`;const p=state.weather?.points?.duong_dong;if(p?.temperature!=null)$('#protoWeather').innerHTML=`${ic('sun-medium')}<div><b>${p.temperature}°C</b><small>Phú Quốc</small></div>`;render()}
function bind(){document.addEventListener('click',ev=>{const s=ev.target.closest('[data-screen]');if(s)return go(s.dataset.screen);const p=ev.target.closest('[data-proto]');if(p)return go(p.dataset.proto);const m=ev.target.closest('[data-mobile-screen]');if(m)return go(m.dataset.mobileScreen);const pv=ev.target.closest('[data-preview]');if(pv){state.preview=pv.dataset.preview;$('#reviewStage').className='review-stage '+state.preview;$$('[data-preview]').forEach(b=>b.classList.toggle('active',b.dataset.preview===state.preview));return}if(ev.target.closest('#mobileMenu'))return $('#reviewSidebar').classList.toggle('open');if(ev.target.closest('#toggleNotes')){$('#reviewNotes').hidden=!$('#reviewNotes').hidden;return}if(ev.target.closest('#closeNotes')){$('#reviewNotes').hidden=true;return}});$('#screenSearch').addEventListener('input',ev=>buildNav(ev.target.value));window.addEventListener('hashchange',()=>{const id=location.hash.replace('#screen=','');if(id&&id!==state.screen)go(id)});}
function init(){const fromHash=location.hash.replace('#screen=','');if(SCREEN_META.some(x=>x[1]===fromHash))state.screen=fromHash;buildNav();bind();render();sync();setInterval(sync,C.refreshMs||120000)}
init();
})();
